name: Build for Mac

on:
  workflow_call:
    inputs:
      tag:
        description: "tag"
        required: false
        default: ""
        type: string
  workflow_dispatch:

jobs:
  build-mac-app:
    name: Release Mac
    runs-on: macos-26
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Setup flutter
        uses: subosito/flutter-action@efb35369e0ad2afab669f228072c1b0d510eae64 # v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Set and Extract version
        shell: pwsh
        run: lib/scripts/build.ps1

      - name: Apply Patch
        shell: pwsh
        run: lib/scripts/patch.ps1 macOS

      - name: Build Mac
        run: flutter build macos --release --dart-define-from-file=skf_release.json

      - name: Prepare Upload
        run: |
          npm install --global create-dmg
          create-dmg build/macos/Build/Products/Release/SakuraKono.app

      - name: Rename DMG
        run: mv SakuraKono*.dmg SakuraKono_macos_${{ env.version }}.dmg

      - name: Release
        if: ${{ github.event.inputs.tag != '' }}
        uses: softprops/action-gh-release@b6effb05e454b25005698d916606bdc6ffcbf961 # v3
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: ${{ github.event.inputs.tag }}
          files: |
            SakuraKono_macos_*.dmg

      - name: Upload macos release
        uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7
        with:
          archive: false
          name: macOS-release
          path: SakuraKono_macos_*.dmg
