// Mocks generated by Mockito 5.4.6 from annotations
// in skf/test/repository/audio_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fixnum/fixnum.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:skf/core/models/audio_types.dart' as _i5;
import 'package:skf/core/repository/audio_repository.dart' as _i2;
import 'package:skf/core/result/loading_state.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AudioRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioRepository extends _i1.Mock implements _i2.AudioRepository {
  MockAudioRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreAudioPlayUrlResp>> audioPlayUrl({
    required _i6.Int64? oid,
    required List<_i6.Int64>? subId,
    required int? itemType,
    int? qn = 80,
    int? fnval = 4048,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#audioPlayUrl, [], {
              #oid: oid,
              #subId: subId,
              #itemType: itemType,
              #qn: qn,
              #fnval: fnval,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreAudioPlayUrlResp>>.value(
                  _i7.dummyValue<_i4.LoadingState<_i5.CoreAudioPlayUrlResp>>(
                    this,
                    Invocation.method(#audioPlayUrl, [], {
                      #oid: oid,
                      #subId: subId,
                      #itemType: itemType,
                      #qn: qn,
                      #fnval: fnval,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreAudioPlayUrlResp>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreAudioPlaylistResp>> audioPlayList({
    _i5.CoreAudioPlaylistSource? from,
    required _i6.Int64? id,
    _i6.Int64? oid,
    List<_i6.Int64>? subId,
    int? itemType,
    _i5.CoreAudioPageOption? pageOpt,
    _i6.Int64? extraId,
    String? next,
    int? qn = 80,
    int? fnval = 4048,
    _i5.CoreAudioListOrder? order = _i5.CoreAudioListOrder.orderNormal,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#audioPlayList, [], {
              #from: from,
              #id: id,
              #oid: oid,
              #subId: subId,
              #itemType: itemType,
              #pageOpt: pageOpt,
              #extraId: extraId,
              #next: next,
              #qn: qn,
              #fnval: fnval,
              #order: order,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreAudioPlaylistResp>>.value(
                  _i7.dummyValue<_i4.LoadingState<_i5.CoreAudioPlaylistResp>>(
                    this,
                    Invocation.method(#audioPlayList, [], {
                      #from: from,
                      #id: id,
                      #oid: oid,
                      #subId: subId,
                      #itemType: itemType,
                      #pageOpt: pageOpt,
                      #extraId: extraId,
                      #next: next,
                      #qn: qn,
                      #fnval: fnval,
                      #order: order,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreAudioPlaylistResp>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreAudioThumbUpResp>> audioThumbUp({
    required _i6.Int64? oid,
    required List<_i6.Int64>? subId,
    required int? itemType,
    required _i5.CoreAudioThumbType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#audioThumbUp, [], {
              #oid: oid,
              #subId: subId,
              #itemType: itemType,
              #type: type,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreAudioThumbUpResp>>.value(
                  _i7.dummyValue<_i4.LoadingState<_i5.CoreAudioThumbUpResp>>(
                    this,
                    Invocation.method(#audioThumbUp, [], {
                      #oid: oid,
                      #subId: subId,
                      #itemType: itemType,
                      #type: type,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreAudioThumbUpResp>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreAudioTripleLikeResp>> audioTripleLike({
    required _i6.Int64? oid,
    required List<_i6.Int64>? subId,
    required int? itemType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#audioTripleLike, [], {
              #oid: oid,
              #subId: subId,
              #itemType: itemType,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreAudioTripleLikeResp>>.value(
                  _i7.dummyValue<_i4.LoadingState<_i5.CoreAudioTripleLikeResp>>(
                    this,
                    Invocation.method(#audioTripleLike, [], {
                      #oid: oid,
                      #subId: subId,
                      #itemType: itemType,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreAudioTripleLikeResp>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreAudioCoinAddResp>> audioCoinAdd({
    required _i6.Int64? oid,
    required List<_i6.Int64>? subId,
    required int? itemType,
    required int? num,
    bool? thumbUp = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#audioCoinAdd, [], {
              #oid: oid,
              #subId: subId,
              #itemType: itemType,
              #num: num,
              #thumbUp: thumbUp,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreAudioCoinAddResp>>.value(
                  _i7.dummyValue<_i4.LoadingState<_i5.CoreAudioCoinAddResp>>(
                    this,
                    Invocation.method(#audioCoinAdd, [], {
                      #oid: oid,
                      #subId: subId,
                      #itemType: itemType,
                      #num: num,
                      #thumbUp: thumbUp,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreAudioCoinAddResp>>);
}
