// Mocks generated by Mockito 5.4.6 from annotations
// in skf/test/repository/auth_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:skf/core/models/auth_types.dart' as _i6;
import 'package:skf/core/repository/auth_repository.dart' as _i2;
import 'package:skf/core/result/loading_state.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.LoadingState<({String authCode, String url})>> getQRCode() =>
      (super.noSuchMethod(
            Invocation.method(#getQRCode, []),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<({String authCode, String url})>
                >.value(
                  _i5.dummyValue<
                    _i4.LoadingState<({String authCode, String url})>
                  >(this, Invocation.method(#getQRCode, [])),
                ),
          )
          as _i3.Future<_i4.LoadingState<({String authCode, String url})>>);

  @override
  _i3.Future<Map<dynamic, dynamic>> pollQRCode(String? authCode) =>
      (super.noSuchMethod(
            Invocation.method(#pollQRCode, [authCode]),
            returnValue: _i3.Future<Map<dynamic, dynamic>>.value(
              <dynamic, dynamic>{},
            ),
          )
          as _i3.Future<Map<dynamic, dynamic>>);

  @override
  _i3.Future<Map<dynamic, dynamic>> loginByPassword(
    String? username,
    String? password,
    String? key,
    String? salt, {
    String? geeChallenge,
    String? geeSeccode,
    String? geeValidate,
    String? recaptchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #loginByPassword,
              [username, password, key, salt],
              {
                #geeChallenge: geeChallenge,
                #geeSeccode: geeSeccode,
                #geeValidate: geeValidate,
                #recaptchaToken: recaptchaToken,
              },
            ),
            returnValue: _i3.Future<Map<dynamic, dynamic>>.value(
              <dynamic, dynamic>{},
            ),
          )
          as _i3.Future<Map<dynamic, dynamic>>);

  @override
  _i3.Future<Map<dynamic, dynamic>> loginBySms(
    String? captchaKey,
    String? tel,
    String? code,
    Object? cid,
    String? key,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loginBySms, [captchaKey, tel, code, cid, key]),
            returnValue: _i3.Future<Map<dynamic, dynamic>>.value(
              <dynamic, dynamic>{},
            ),
          )
          as _i3.Future<Map<dynamic, dynamic>>);

  @override
  _i3.Future<Map<dynamic, dynamic>> sendSmsCode(
    Object? cid,
    String? tel, {
    String? geeChallenge,
    String? geeSeccode,
    String? geeValidate,
    String? recaptchaToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendSmsCode,
              [cid, tel],
              {
                #geeChallenge: geeChallenge,
                #geeSeccode: geeSeccode,
                #geeValidate: geeValidate,
                #recaptchaToken: recaptchaToken,
              },
            ),
            returnValue: _i3.Future<Map<dynamic, dynamic>>.value(
              <dynamic, dynamic>{},
            ),
          )
          as _i3.Future<Map<dynamic, dynamic>>);

  @override
  _i3.Future<Map<dynamic, dynamic>> queryCaptcha() =>
      (super.noSuchMethod(
            Invocation.method(#queryCaptcha, []),
            returnValue: _i3.Future<Map<dynamic, dynamic>>.value(
              <dynamic, dynamic>{},
            ),
          )
          as _i3.Future<Map<dynamic, dynamic>>);

  @override
  _i3.Future<Map<dynamic, dynamic>> getWebKey() =>
      (super.noSuchMethod(
            Invocation.method(#getWebKey, []),
            returnValue: _i3.Future<Map<dynamic, dynamic>>.value(
              <dynamic, dynamic>{},
            ),
          )
          as _i3.Future<Map<dynamic, dynamic>>);

  @override
  _i3.Future<Map<dynamic, dynamic>> logout(_i6.CoreAccount? account) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [account]),
            returnValue: _i3.Future<Map<dynamic, dynamic>>.value(
              <dynamic, dynamic>{},
            ),
          )
          as _i3.Future<Map<dynamic, dynamic>>);

  @override
  _i3.Future<_i4.LoadingState<_i6.CoreLoginDevicesData>> loginDevices() =>
      (super.noSuchMethod(
            Invocation.method(#loginDevices, []),
            returnValue:
                _i3.Future<_i4.LoadingState<_i6.CoreLoginDevicesData>>.value(
                  _i5.dummyValue<_i4.LoadingState<_i6.CoreLoginDevicesData>>(
                    this,
                    Invocation.method(#loginDevices, []),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i6.CoreLoginDevicesData>>);

  @override
  _i3.Future<Map<dynamic, dynamic>> safeCenterGetInfo(String? tmpCode) =>
      (super.noSuchMethod(
            Invocation.method(#safeCenterGetInfo, [tmpCode]),
            returnValue: _i3.Future<Map<dynamic, dynamic>>.value(
              <dynamic, dynamic>{},
            ),
          )
          as _i3.Future<Map<dynamic, dynamic>>);

  @override
  _i3.Future<Map<dynamic, dynamic>> preCapture() =>
      (super.noSuchMethod(
            Invocation.method(#preCapture, []),
            returnValue: _i3.Future<Map<dynamic, dynamic>>.value(
              <dynamic, dynamic>{},
            ),
          )
          as _i3.Future<Map<dynamic, dynamic>>);

  @override
  _i3.Future<Map<dynamic, dynamic>> safeCenterSmsCode({
    String? smsType,
    required String? tmpCode,
    String? geeChallenge,
    String? geeSeccode,
    String? geeValidate,
    String? recaptchaToken,
    required String? refererUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#safeCenterSmsCode, [], {
              #smsType: smsType,
              #tmpCode: tmpCode,
              #geeChallenge: geeChallenge,
              #geeSeccode: geeSeccode,
              #geeValidate: geeValidate,
              #recaptchaToken: recaptchaToken,
              #refererUrl: refererUrl,
            }),
            returnValue: _i3.Future<Map<dynamic, dynamic>>.value(
              <dynamic, dynamic>{},
            ),
          )
          as _i3.Future<Map<dynamic, dynamic>>);

  @override
  _i3.Future<Map<dynamic, dynamic>> safeCenterSmsVerify({
    String? type,
    required String? code,
    required String? tmpCode,
    required String? requestId,
    required String? source,
    required String? captchaKey,
    required String? refererUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#safeCenterSmsVerify, [], {
              #type: type,
              #code: code,
              #tmpCode: tmpCode,
              #requestId: requestId,
              #source: source,
              #captchaKey: captchaKey,
              #refererUrl: refererUrl,
            }),
            returnValue: _i3.Future<Map<dynamic, dynamic>>.value(
              <dynamic, dynamic>{},
            ),
          )
          as _i3.Future<Map<dynamic, dynamic>>);

  @override
  _i3.Future<Map<dynamic, dynamic>> oauth2AccessToken(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#oauth2AccessToken, [code]),
            returnValue: _i3.Future<Map<dynamic, dynamic>>.value(
              <dynamic, dynamic>{},
            ),
          )
          as _i3.Future<Map<dynamic, dynamic>>);
}
