// Mocks generated by Mockito 5.4.6 from annotations
// in skf/test/repository/black_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:skf/core/models/black_status.dart' as _i7;
import 'package:skf/core/models/blacklist_data.dart' as _i5;
import 'package:skf/core/repository/black_repository.dart' as _i2;
import 'package:skf/core/result/loading_state.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BlackRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlackRepository extends _i1.Mock implements _i2.BlackRepository {
  MockBlackRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreBlackListData>> blackList({
    required int? pn,
    int? ps = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#blackList, [], {#pn: pn, #ps: ps}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreBlackListData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreBlackListData>>(
                    this,
                    Invocation.method(#blackList, [], {#pn: pn, #ps: ps}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreBlackListData>>);

  @override
  _i3.Future<_i4.LoadingState<void>> addBlack({required int? uid}) =>
      (super.noSuchMethod(
            Invocation.method(#addBlack, [], {#uid: uid}),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#addBlack, [], {#uid: uid}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> removeBlack({required int? uid}) =>
      (super.noSuchMethod(
            Invocation.method(#removeBlack, [], {#uid: uid}),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#removeBlack, [], {#uid: uid}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<_i7.CoreBlackStatus>> checkBlack({
    required int? uid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#checkBlack, [], {#uid: uid}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i7.CoreBlackStatus>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i7.CoreBlackStatus>>(
                    this,
                    Invocation.method(#checkBlack, [], {#uid: uid}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i7.CoreBlackStatus>>);
}
