// Mocks generated by Mockito 5.4.6 from annotations
// in skf/test/repository/danmaku_filter_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:skf/core/models/danmaku_block.dart' as _i5;
import 'package:skf/core/repository/danmaku_filter_repository.dart' as _i2;
import 'package:skf/core/result/loading_state.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DanmakuFilterRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDanmakuFilterRepository extends _i1.Mock
    implements _i2.DanmakuFilterRepository {
  MockDanmakuFilterRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreDanmakuBlockDataModel>> danmakuFilter() =>
      (super.noSuchMethod(
            Invocation.method(#danmakuFilter, []),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<_i5.CoreDanmakuBlockDataModel>
                >.value(
                  _i6.dummyValue<
                    _i4.LoadingState<_i5.CoreDanmakuBlockDataModel>
                  >(this, Invocation.method(#danmakuFilter, [])),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreDanmakuBlockDataModel>>);

  @override
  _i3.Future<_i4.LoadingState<void>> danmakuFilterDel({required int? ids}) =>
      (super.noSuchMethod(
            Invocation.method(#danmakuFilterDel, [], {#ids: ids}),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#danmakuFilterDel, [], {#ids: ids}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreSimpleRule>> danmakuFilterAdd({
    required String? filter,
    required int? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#danmakuFilterAdd, [], {
              #filter: filter,
              #type: type,
            }),
            returnValue: _i3.Future<_i4.LoadingState<_i5.CoreSimpleRule>>.value(
              _i6.dummyValue<_i4.LoadingState<_i5.CoreSimpleRule>>(
                this,
                Invocation.method(#danmakuFilterAdd, [], {
                  #filter: filter,
                  #type: type,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreSimpleRule>>);
}
