// Mocks generated by Mockito 5.4.6 from annotations
// in skf/test/repository/danmaku_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:skf/core/models/danmaku_types.dart' as _i5;
import 'package:skf/core/repository/danmaku_repository.dart' as _i2;
import 'package:skf/core/result/loading_state.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DanmakuRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDanmakuRepository extends _i1.Mock implements _i2.DanmakuRepository {
  MockDanmakuRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreDanmakuPost>> shootDanmaku({
    int? type = 1,
    required int? oid,
    required String? msg,
    int? mode = 1,
    required String? bvid,
    int? progress,
    int? color,
    int? fontSize,
    int? pool,
    bool? colorful = false,
    int? checkboxType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#shootDanmaku, [], {
              #type: type,
              #oid: oid,
              #msg: msg,
              #mode: mode,
              #bvid: bvid,
              #progress: progress,
              #color: color,
              #fontSize: fontSize,
              #pool: pool,
              #colorful: colorful,
              #checkboxType: checkboxType,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreDanmakuPost>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreDanmakuPost>>(
                    this,
                    Invocation.method(#shootDanmaku, [], {
                      #type: type,
                      #oid: oid,
                      #msg: msg,
                      #mode: mode,
                      #bvid: bvid,
                      #progress: progress,
                      #color: color,
                      #fontSize: fontSize,
                      #pool: pool,
                      #colorful: colorful,
                      #checkboxType: checkboxType,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreDanmakuPost>>);

  @override
  _i3.Future<_i4.LoadingState<void>> danmakuLike({
    required bool? isLike,
    required int? cid,
    required int? id,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#danmakuLike, [], {
              #isLike: isLike,
              #cid: cid,
              #id: id,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#danmakuLike, [], {
                  #isLike: isLike,
                  #cid: cid,
                  #id: id,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> danmakuReport({
    required int? reason,
    required int? cid,
    required int? id,
    bool? block = false,
    String? content,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#danmakuReport, [], {
              #reason: reason,
              #cid: cid,
              #id: id,
              #block: block,
              #content: content,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#danmakuReport, [], {
                  #reason: reason,
                  #cid: cid,
                  #id: id,
                  #block: block,
                  #content: content,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<String?>> danmakuRecall({
    required int? cid,
    required int? id,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#danmakuRecall, [], {#cid: cid, #id: id}),
            returnValue: _i3.Future<_i4.LoadingState<String?>>.value(
              _i6.dummyValue<_i4.LoadingState<String?>>(
                this,
                Invocation.method(#danmakuRecall, [], {#cid: cid, #id: id}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<String?>>);

  @override
  _i3.Future<_i4.LoadingState<String?>> danmakuEditState({
    required int? oid,
    required Iterable<int>? ids,
    required int? state,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#danmakuEditState, [], {
              #oid: oid,
              #ids: ids,
              #state: state,
            }),
            returnValue: _i3.Future<_i4.LoadingState<String?>>.value(
              _i6.dummyValue<_i4.LoadingState<String?>>(
                this,
                Invocation.method(#danmakuEditState, [], {
                  #oid: oid,
                  #ids: ids,
                  #state: state,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<String?>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreDanmakuSegmentReply>> dmSegMobile({
    required int? cid,
    required int? segmentIndex,
    int? type = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#dmSegMobile, [], {
              #cid: cid,
              #segmentIndex: segmentIndex,
              #type: type,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreDanmakuSegmentReply>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreDanmakuSegmentReply>>(
                    this,
                    Invocation.method(#dmSegMobile, [], {
                      #cid: cid,
                      #segmentIndex: segmentIndex,
                      #type: type,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreDanmakuSegmentReply>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreDanmakuViewReply>> dmView(
    int? aid,
    int? cid,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#dmView, [aid, cid]),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreDanmakuViewReply>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreDanmakuViewReply>>(
                    this,
                    Invocation.method(#dmView, [aid, cid]),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreDanmakuViewReply>>);
}
