// Mocks generated by Mockito 5.4.6 from annotations
// in skf/test/repository/dynamics_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:skf/common/widgets/pair.dart' as _i7;
import 'package:skf/core/models/dynamics_types.dart' as _i5;
import 'package:skf/core/repository/dynamics_repository.dart' as _i2;
import 'package:skf/core/result/loading_state.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DynamicsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDynamicsRepository extends _i1.Mock
    implements _i2.DynamicsRepository {
  MockDynamicsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreDynamicsDataModel>> followDynamic({
    int? hostMid,
    String? offset,
    Set<int>? tempBannedList,
    _i5.CoreDynamicsTabType? type = _i5.CoreDynamicsTabType.all,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#followDynamic, [], {
              #hostMid: hostMid,
              #offset: offset,
              #tempBannedList: tempBannedList,
              #type: type,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreDynamicsDataModel>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreDynamicsDataModel>>(
                    this,
                    Invocation.method(#followDynamic, [], {
                      #hostMid: hostMid,
                      #offset: offset,
                      #tempBannedList: tempBannedList,
                      #type: type,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreDynamicsDataModel>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreFollowUpModel>> followUp() =>
      (super.noSuchMethod(
            Invocation.method(#followUp, []),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreFollowUpModel>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreFollowUpModel>>(
                    this,
                    Invocation.method(#followUp, []),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreFollowUpModel>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreFollowUpModel>> dynUpList(
    String? offset,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#dynUpList, [offset]),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreFollowUpModel>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreFollowUpModel>>(
                    this,
                    Invocation.method(#dynUpList, [offset]),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreFollowUpModel>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreFollowUpModel>> followings({
    int? vmid,
    int? pn,
    int? ps = 20,
    String? orderType = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#followings, [], {
              #vmid: vmid,
              #pn: pn,
              #ps: ps,
              #orderType: orderType,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreFollowUpModel>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreFollowUpModel>>(
                    this,
                    Invocation.method(#followings, [], {
                      #vmid: vmid,
                      #pn: pn,
                      #ps: ps,
                      #orderType: orderType,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreFollowUpModel>>);

  @override
  _i3.Future<_i4.LoadingState<void>> thumbDynamic({
    required String? dynamicId,
    required int? up,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#thumbDynamic, [], {
              #dynamicId: dynamicId,
              #up: up,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#thumbDynamic, [], {
                  #dynamicId: dynamicId,
                  #up: up,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<Map<dynamic, dynamic>?>> createDynamic({
    int? mid,
    String? dynIdStr,
    Object? rid,
    Object? dynType,
    String? rawText,
    List<dynamic>? pics,
    int? publishTime,
    _i5.CoreReplyOptionType? replyOption,
    int? privatePub,
    List<Map<String, dynamic>>? extraContent,
    _i7.Pair<int, String>? topic,
    String? title,
    Map<dynamic, dynamic>? attachCard,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createDynamic, [], {
              #mid: mid,
              #dynIdStr: dynIdStr,
              #rid: rid,
              #dynType: dynType,
              #rawText: rawText,
              #pics: pics,
              #publishTime: publishTime,
              #replyOption: replyOption,
              #privatePub: privatePub,
              #extraContent: extraContent,
              #topic: topic,
              #title: title,
              #attachCard: attachCard,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<Map<dynamic, dynamic>?>>.value(
                  _i6.dummyValue<_i4.LoadingState<Map<dynamic, dynamic>?>>(
                    this,
                    Invocation.method(#createDynamic, [], {
                      #mid: mid,
                      #dynIdStr: dynIdStr,
                      #rid: rid,
                      #dynType: dynType,
                      #rawText: rawText,
                      #pics: pics,
                      #publishTime: publishTime,
                      #replyOption: replyOption,
                      #privatePub: privatePub,
                      #extraContent: extraContent,
                      #topic: topic,
                      #title: title,
                      #attachCard: attachCard,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<Map<dynamic, dynamic>?>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreDynamicItemModel>> dynamicDetail({
    Object? id,
    dynamic rid,
    Object? type,
    bool? clearCookie = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#dynamicDetail, [], {
              #id: id,
              #rid: rid,
              #type: type,
              #clearCookie: clearCookie,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreDynamicItemModel>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreDynamicItemModel>>(
                    this,
                    Invocation.method(#dynamicDetail, [], {
                      #id: id,
                      #rid: rid,
                      #type: type,
                      #clearCookie: clearCookie,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreDynamicItemModel>>);

  @override
  _i3.Future<_i4.LoadingState<void>> setTop({required Object? dynamicId}) =>
      (super.noSuchMethod(
            Invocation.method(#setTop, [], {#dynamicId: dynamicId}),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#setTop, [], {#dynamicId: dynamicId}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> rmTop({required Object? dynamicId}) =>
      (super.noSuchMethod(
            Invocation.method(#rmTop, [], {#dynamicId: dynamicId}),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#rmTop, [], {#dynamicId: dynamicId}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreArticleInfoData>> articleInfo({
    required Object? cvId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#articleInfo, [], {#cvId: cvId}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreArticleInfoData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreArticleInfoData>>(
                    this,
                    Invocation.method(#articleInfo, [], {#cvId: cvId}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreArticleInfoData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreArticleViewData>> articleView({
    required Object? cvId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#articleView, [], {#cvId: cvId}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreArticleViewData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreArticleViewData>>(
                    this,
                    Invocation.method(#articleView, [], {#cvId: cvId}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreArticleViewData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreDynamicItemModel>> opusDetail({
    required Object? opusId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#opusDetail, [], {#opusId: opusId}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreDynamicItemModel>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreDynamicItemModel>>(
                    this,
                    Invocation.method(#opusDetail, [], {#opusId: opusId}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreDynamicItemModel>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreVoteInfo>> voteInfo(int? voteId) =>
      (super.noSuchMethod(
            Invocation.method(#voteInfo, [voteId]),
            returnValue: _i3.Future<_i4.LoadingState<_i5.CoreVoteInfo>>.value(
              _i6.dummyValue<_i4.LoadingState<_i5.CoreVoteInfo>>(
                this,
                Invocation.method(#voteInfo, [voteId]),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreVoteInfo>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreVoteInfo>> doVote({
    required int? voteId,
    required List<int>? votes,
    bool? anonymous = false,
    int? dynamicId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#doVote, [], {
              #voteId: voteId,
              #votes: votes,
              #anonymous: anonymous,
              #dynamicId: dynamicId,
            }),
            returnValue: _i3.Future<_i4.LoadingState<_i5.CoreVoteInfo>>.value(
              _i6.dummyValue<_i4.LoadingState<_i5.CoreVoteInfo>>(
                this,
                Invocation.method(#doVote, [], {
                  #voteId: voteId,
                  #votes: votes,
                  #anonymous: anonymous,
                  #dynamicId: dynamicId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreVoteInfo>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreTopDetails?>> topicTop({
    required Object? topicId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#topicTop, [], {#topicId: topicId}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreTopDetails?>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreTopDetails?>>(
                    this,
                    Invocation.method(#topicTop, [], {#topicId: topicId}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreTopDetails?>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreTopicCardList?>> topicFeed({
    required Object? topicId,
    String? offset,
    required int? sortBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#topicFeed, [], {
              #topicId: topicId,
              #offset: offset,
              #sortBy: sortBy,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreTopicCardList?>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreTopicCardList?>>(
                    this,
                    Invocation.method(#topicFeed, [], {
                      #topicId: topicId,
                      #offset: offset,
                      #sortBy: sortBy,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreTopicCardList?>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreTopicCardList?>> topicFold({
    required Object? topicId,
    required int? sortBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#topicFold, [], {
              #topicId: topicId,
              #sortBy: sortBy,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreTopicCardList?>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreTopicCardList?>>(
                    this,
                    Invocation.method(#topicFold, [], {
                      #topicId: topicId,
                      #sortBy: sortBy,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreTopicCardList?>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreArticleListData>> articleList({
    required Object? id,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#articleList, [], {#id: id}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreArticleListData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreArticleListData>>(
                    this,
                    Invocation.method(#articleList, [], {#id: id}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreArticleListData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreDynReserveData>> dynReserve({
    required Object? reserveId,
    required Object? curBtnStatus,
    required Object? dynamicIdStr,
    required Object? reserveTotal,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#dynReserve, [], {
              #reserveId: reserveId,
              #curBtnStatus: curBtnStatus,
              #dynamicIdStr: dynamicIdStr,
              #reserveTotal: reserveTotal,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreDynReserveData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreDynReserveData>>(
                    this,
                    Invocation.method(#dynReserve, [], {
                      #reserveId: reserveId,
                      #curBtnStatus: curBtnStatus,
                      #dynamicIdStr: dynamicIdStr,
                      #reserveTotal: reserveTotal,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreDynReserveData>>);

  @override
  _i3.Future<_i4.LoadingState<List<_i5.CoreTopicItem>?>> dynTopicRcmd({
    int? ps = 25,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#dynTopicRcmd, [], {#ps: ps}),
            returnValue:
                _i3.Future<_i4.LoadingState<List<_i5.CoreTopicItem>?>>.value(
                  _i6.dummyValue<_i4.LoadingState<List<_i5.CoreTopicItem>?>>(
                    this,
                    Invocation.method(#dynTopicRcmd, [], {#ps: ps}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i5.CoreTopicItem>?>>);

  @override
  _i3.Future<_i4.LoadingState<List<_i5.CoreOpusPicModel>?>> dynPic(
    Object? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#dynPic, [id]),
            returnValue:
                _i3.Future<_i4.LoadingState<List<_i5.CoreOpusPicModel>?>>.value(
                  _i6.dummyValue<_i4.LoadingState<List<_i5.CoreOpusPicModel>?>>(
                    this,
                    Invocation.method(#dynPic, [id]),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i5.CoreOpusPicModel>?>>);

  @override
  _i3.Future<_i4.LoadingState<List<_i5.CoreMentionGroup>?>> dynMention({
    String? keyword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#dynMention, [], {#keyword: keyword}),
            returnValue:
                _i3.Future<_i4.LoadingState<List<_i5.CoreMentionGroup>?>>.value(
                  _i6.dummyValue<_i4.LoadingState<List<_i5.CoreMentionGroup>?>>(
                    this,
                    Invocation.method(#dynMention, [], {#keyword: keyword}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i5.CoreMentionGroup>?>>);

  @override
  _i3.Future<_i4.LoadingState<int?>> createVote(_i5.CoreVoteInfo? voteInfo) =>
      (super.noSuchMethod(
            Invocation.method(#createVote, [voteInfo]),
            returnValue: _i3.Future<_i4.LoadingState<int?>>.value(
              _i6.dummyValue<_i4.LoadingState<int?>>(
                this,
                Invocation.method(#createVote, [voteInfo]),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<int?>>);

  @override
  _i3.Future<_i4.LoadingState<int?>> updateVote(_i5.CoreVoteInfo? voteInfo) =>
      (super.noSuchMethod(
            Invocation.method(#updateVote, [voteInfo]),
            returnValue: _i3.Future<_i4.LoadingState<int?>>.value(
              _i6.dummyValue<_i4.LoadingState<int?>>(
                this,
                Invocation.method(#updateVote, [voteInfo]),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<int?>>);

  @override
  _i3.Future<_i4.LoadingState<int?>> createReserve({
    int? subType = 0,
    required String? title,
    required int? livePlanStartTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createReserve, [], {
              #subType: subType,
              #title: title,
              #livePlanStartTime: livePlanStartTime,
            }),
            returnValue: _i3.Future<_i4.LoadingState<int?>>.value(
              _i6.dummyValue<_i4.LoadingState<int?>>(
                this,
                Invocation.method(#createReserve, [], {
                  #subType: subType,
                  #title: title,
                  #livePlanStartTime: livePlanStartTime,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<int?>>);

  @override
  _i3.Future<_i4.LoadingState<int?>> updateReserve({
    int? subType = 0,
    required String? title,
    required int? livePlanStartTime,
    required int? sid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateReserve, [], {
              #subType: subType,
              #title: title,
              #livePlanStartTime: livePlanStartTime,
              #sid: sid,
            }),
            returnValue: _i3.Future<_i4.LoadingState<int?>>.value(
              _i6.dummyValue<_i4.LoadingState<int?>>(
                this,
                Invocation.method(#updateReserve, [], {
                  #subType: subType,
                  #title: title,
                  #livePlanStartTime: livePlanStartTime,
                  #sid: sid,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<int?>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreReserveInfoData>> reserveInfo({
    required int? sid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reserveInfo, [], {#sid: sid}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreReserveInfoData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreReserveInfoData>>(
                    this,
                    Invocation.method(#reserveInfo, [], {#sid: sid}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreReserveInfoData>>);

  @override
  _i3.Future<_i4.LoadingState<List<_i5.CoreFolloweeVote>?>> followeeVotes({
    required dynamic voteId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#followeeVotes, [], {#voteId: voteId}),
            returnValue:
                _i3.Future<_i4.LoadingState<List<_i5.CoreFolloweeVote>?>>.value(
                  _i6.dummyValue<_i4.LoadingState<List<_i5.CoreFolloweeVote>?>>(
                    this,
                    Invocation.method(#followeeVotes, [], {#voteId: voteId}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i5.CoreFolloweeVote>?>>);

  @override
  _i3.Future<_i4.LoadingState<void>> dynPrivatePubSetting({
    required Object? dynId,
    int? dynType,
    required String? action,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#dynPrivatePubSetting, [], {
              #dynId: dynId,
              #dynType: dynType,
              #action: action,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#dynPrivatePubSetting, [], {
                  #dynId: dynId,
                  #dynType: dynType,
                  #action: action,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> editDyn({
    required Object? dynId,
    Object? repostDynId,
    String? rawText,
    List<dynamic>? pics,
    _i5.CoreReplyOptionType? replyOption,
    int? privatePub,
    List<Map<String, dynamic>>? extraContent,
    _i7.Pair<int, String>? topic,
    String? title,
    Map<dynamic, dynamic>? attachCard,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#editDyn, [], {
              #dynId: dynId,
              #repostDynId: repostDynId,
              #rawText: rawText,
              #pics: pics,
              #replyOption: replyOption,
              #privatePub: privatePub,
              #extraContent: extraContent,
              #topic: topic,
              #title: title,
              #attachCard: attachCard,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#editDyn, [], {
                  #dynId: dynId,
                  #repostDynId: repostDynId,
                  #rawText: rawText,
                  #pics: pics,
                  #replyOption: replyOption,
                  #privatePub: privatePub,
                  #extraContent: extraContent,
                  #topic: topic,
                  #title: title,
                  #attachCard: attachCard,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreBubbleData>> bubble({
    required Object? tribeId,
    Object? categoryId,
    int? sortType,
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#bubble, [], {
              #tribeId: tribeId,
              #categoryId: categoryId,
              #sortType: sortType,
              #page: page,
            }),
            returnValue: _i3.Future<_i4.LoadingState<_i5.CoreBubbleData>>.value(
              _i6.dummyValue<_i4.LoadingState<_i5.CoreBubbleData>>(
                this,
                Invocation.method(#bubble, [], {
                  #tribeId: tribeId,
                  #categoryId: categoryId,
                  #sortType: sortType,
                  #page: page,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreBubbleData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreDynReactionData>> dynReaction({
    required Object? id,
    String? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#dynReaction, [], {#id: id, #offset: offset}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreDynReactionData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreDynReactionData>>(
                    this,
                    Invocation.method(#dynReaction, [], {
                      #id: id,
                      #offset: offset,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreDynReactionData>>);

  @override
  _i3.Future<int?> dynRed() =>
      (super.noSuchMethod(
            Invocation.method(#dynRed, []),
            returnValue: _i3.Future<int?>.value(),
          )
          as _i3.Future<int?>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreOpusDetailResp>> opusDetailGrpc({
    _i5.CoreOpusType? opusType,
    required int? oid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#opusDetailGrpc, [], {
              #opusType: opusType,
              #oid: oid,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreOpusDetailResp>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreOpusDetailResp>>(
                    this,
                    Invocation.method(#opusDetailGrpc, [], {
                      #opusType: opusType,
                      #oid: oid,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreOpusDetailResp>>);
}
