// Mocks generated by Mockito 5.4.6 from annotations
// in skf/test/repository/fav_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:skf/core/models/fav_types.dart' as _i6;
import 'package:skf/core/repository/fav_repository.dart' as _i2;
import 'package:skf/core/result/loading_state.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FavRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavRepository extends _i1.Mock implements _i2.FavRepository {
  MockFavRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.LoadingState<void>> favFavFolder(Object? mediaId) =>
      (super.noSuchMethod(
            Invocation.method(#favFavFolder, [mediaId]),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i5.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#favFavFolder, [mediaId]),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> unfavFavFolder(Object? mediaId) =>
      (super.noSuchMethod(
            Invocation.method(#unfavFavFolder, [mediaId]),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i5.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#unfavFavFolder, [mediaId]),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<_i6.CoreFavDetailData>> userFavFolderDetail({
    required int? mediaId,
    required int? pn,
    required int? ps,
    String? keyword = '',
    _i6.CoreFavOrderType? order = _i6.CoreFavOrderType.mtime,
    int? type = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#userFavFolderDetail, [], {
              #mediaId: mediaId,
              #pn: pn,
              #ps: ps,
              #keyword: keyword,
              #order: order,
              #type: type,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i6.CoreFavDetailData>>.value(
                  _i5.dummyValue<_i4.LoadingState<_i6.CoreFavDetailData>>(
                    this,
                    Invocation.method(#userFavFolderDetail, [], {
                      #mediaId: mediaId,
                      #pn: pn,
                      #ps: ps,
                      #keyword: keyword,
                      #order: order,
                      #type: type,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i6.CoreFavDetailData>>);

  @override
  _i3.Future<_i4.LoadingState<void>> cancelSub({
    required int? id,
    required int? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#cancelSub, [], {#id: id, #type: type}),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i5.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#cancelSub, [], {#id: id, #type: type}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<_i6.CoreSubDetailData>> favSeasonList({
    required int? id,
    required int? pn,
    required int? ps,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#favSeasonList, [], {#id: id, #pn: pn, #ps: ps}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i6.CoreSubDetailData>>.value(
                  _i5.dummyValue<_i4.LoadingState<_i6.CoreSubDetailData>>(
                    this,
                    Invocation.method(#favSeasonList, [], {
                      #id: id,
                      #pn: pn,
                      #ps: ps,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i6.CoreSubDetailData>>);

  @override
  _i3.Future<_i4.LoadingState<_i6.CoreSpaceCheeseData>> favPugv({
    required int? mid,
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#favPugv, [], {#mid: mid, #page: page}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i6.CoreSpaceCheeseData>>.value(
                  _i5.dummyValue<_i4.LoadingState<_i6.CoreSpaceCheeseData>>(
                    this,
                    Invocation.method(#favPugv, [], {#mid: mid, #page: page}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i6.CoreSpaceCheeseData>>);

  @override
  _i3.Future<_i4.LoadingState<void>> addFavPugv(Object? seasonId) =>
      (super.noSuchMethod(
            Invocation.method(#addFavPugv, [seasonId]),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i5.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#addFavPugv, [seasonId]),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> delFavPugv(Object? seasonId) =>
      (super.noSuchMethod(
            Invocation.method(#delFavPugv, [seasonId]),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i5.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#delFavPugv, [seasonId]),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<_i6.CoreFavTopicData>> favTopic({
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#favTopic, [], {#page: page}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i6.CoreFavTopicData>>.value(
                  _i5.dummyValue<_i4.LoadingState<_i6.CoreFavTopicData>>(
                    this,
                    Invocation.method(#favTopic, [], {#page: page}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i6.CoreFavTopicData>>);

  @override
  _i3.Future<_i4.LoadingState<void>> addFavTopic(Object? topicId) =>
      (super.noSuchMethod(
            Invocation.method(#addFavTopic, [topicId]),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i5.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#addFavTopic, [topicId]),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> delFavTopic(Object? topicId) =>
      (super.noSuchMethod(
            Invocation.method(#delFavTopic, [topicId]),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i5.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#delFavTopic, [topicId]),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> likeTopic(Object? topicId, bool? isLike) =>
      (super.noSuchMethod(
            Invocation.method(#likeTopic, [topicId, isLike]),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i5.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#likeTopic, [topicId, isLike]),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<_i6.CoreFavArticleData>> favArticle({
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#favArticle, [], {#page: page}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i6.CoreFavArticleData>>.value(
                  _i5.dummyValue<_i4.LoadingState<_i6.CoreFavArticleData>>(
                    this,
                    Invocation.method(#favArticle, [], {#page: page}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i6.CoreFavArticleData>>);

  @override
  _i3.Future<_i4.LoadingState<void>> addFavArticle({required Object? id}) =>
      (super.noSuchMethod(
            Invocation.method(#addFavArticle, [], {#id: id}),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i5.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#addFavArticle, [], {#id: id}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> delFavArticle({required Object? id}) =>
      (super.noSuchMethod(
            Invocation.method(#delFavArticle, [], {#id: id}),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i5.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#delFavArticle, [], {#id: id}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<List<_i6.CoreFavNoteItemModel>?>> userNoteList({
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#userNoteList, [], {#page: page}),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<List<_i6.CoreFavNoteItemModel>?>
                >.value(
                  _i5.dummyValue<
                    _i4.LoadingState<List<_i6.CoreFavNoteItemModel>?>
                  >(this, Invocation.method(#userNoteList, [], {#page: page})),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i6.CoreFavNoteItemModel>?>>);

  @override
  _i3.Future<_i4.LoadingState<List<_i6.CoreFavNoteItemModel>?>> noteList({
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#noteList, [], {#page: page}),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<List<_i6.CoreFavNoteItemModel>?>
                >.value(
                  _i5.dummyValue<
                    _i4.LoadingState<List<_i6.CoreFavNoteItemModel>?>
                  >(this, Invocation.method(#noteList, [], {#page: page})),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i6.CoreFavNoteItemModel>?>>);

  @override
  _i3.Future<_i4.LoadingState<void>> delNote({
    required bool? isPublish,
    required String? noteIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delNote, [], {
              #isPublish: isPublish,
              #noteIds: noteIds,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i5.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#delNote, [], {
                  #isPublish: isPublish,
                  #noteIds: noteIds,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<_i6.CoreFavPgcData>> favPgc({
    required int? type,
    required int? pn,
    int? followStatus,
    Object? mid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#favPgc, [], {
              #type: type,
              #pn: pn,
              #followStatus: followStatus,
              #mid: mid,
            }),
            returnValue: _i3.Future<_i4.LoadingState<_i6.CoreFavPgcData>>.value(
              _i5.dummyValue<_i4.LoadingState<_i6.CoreFavPgcData>>(
                this,
                Invocation.method(#favPgc, [], {
                  #type: type,
                  #pn: pn,
                  #followStatus: followStatus,
                  #mid: mid,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<_i6.CoreFavPgcData>>);

  @override
  _i3.Future<_i4.LoadingState<_i6.CoreFavFolderData>> userfavFolder({
    required int? pn,
    required int? ps,
    required dynamic mid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#userfavFolder, [], {
              #pn: pn,
              #ps: ps,
              #mid: mid,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i6.CoreFavFolderData>>.value(
                  _i5.dummyValue<_i4.LoadingState<_i6.CoreFavFolderData>>(
                    this,
                    Invocation.method(#userfavFolder, [], {
                      #pn: pn,
                      #ps: ps,
                      #mid: mid,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i6.CoreFavFolderData>>);

  @override
  _i3.Future<_i4.LoadingState<_i6.CoreFavFolderData>> allFavFolders(
    Object? mid,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#allFavFolders, [mid]),
            returnValue:
                _i3.Future<_i4.LoadingState<_i6.CoreFavFolderData>>.value(
                  _i5.dummyValue<_i4.LoadingState<_i6.CoreFavFolderData>>(
                    this,
                    Invocation.method(#allFavFolders, [mid]),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i6.CoreFavFolderData>>);

  @override
  _i3.Future<_i4.LoadingState<_i6.CoreFavFolderData>> videoInFolder({
    dynamic mid,
    dynamic rid,
    dynamic type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#videoInFolder, [], {
              #mid: mid,
              #rid: rid,
              #type: type,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i6.CoreFavFolderData>>.value(
                  _i5.dummyValue<_i4.LoadingState<_i6.CoreFavFolderData>>(
                    this,
                    Invocation.method(#videoInFolder, [], {
                      #mid: mid,
                      #rid: rid,
                      #type: type,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i6.CoreFavFolderData>>);

  @override
  _i3.Future<_i4.LoadingState<void>> favVideo({
    required String? resources,
    String? addIds,
    String? delIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#favVideo, [], {
              #resources: resources,
              #addIds: addIds,
              #delIds: delIds,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i5.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#favVideo, [], {
                  #resources: resources,
                  #addIds: addIds,
                  #delIds: delIds,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> unfavAll(Object? rid, Object? type) =>
      (super.noSuchMethod(
            Invocation.method(#unfavAll, [rid, type]),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i5.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#unfavAll, [rid, type]),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> seasonFav({
    required bool? isFav,
    required dynamic seasonId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#seasonFav, [], {
              #isFav: isFav,
              #seasonId: seasonId,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i5.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#seasonFav, [], {
                  #isFav: isFav,
                  #seasonId: seasonId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<List<_i6.CoreSpaceFavData>?>> spaceFav({
    required int? mid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#spaceFav, [], {#mid: mid}),
            returnValue:
                _i3.Future<_i4.LoadingState<List<_i6.CoreSpaceFavData>?>>.value(
                  _i5.dummyValue<_i4.LoadingState<List<_i6.CoreSpaceFavData>?>>(
                    this,
                    Invocation.method(#spaceFav, [], {#mid: mid}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i6.CoreSpaceFavData>?>>);

  @override
  _i3.Future<_i4.LoadingState<_i6.CoreFavFolderInfo>> addOrEditFolder({
    required bool? isAdd,
    dynamic mediaId,
    required String? title,
    required int? privacy,
    required String? cover,
    required String? intro,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addOrEditFolder, [], {
              #isAdd: isAdd,
              #mediaId: mediaId,
              #title: title,
              #privacy: privacy,
              #cover: cover,
              #intro: intro,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i6.CoreFavFolderInfo>>.value(
                  _i5.dummyValue<_i4.LoadingState<_i6.CoreFavFolderInfo>>(
                    this,
                    Invocation.method(#addOrEditFolder, [], {
                      #isAdd: isAdd,
                      #mediaId: mediaId,
                      #title: title,
                      #privacy: privacy,
                      #cover: cover,
                      #intro: intro,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i6.CoreFavFolderInfo>>);

  @override
  _i3.Future<_i4.LoadingState<_i6.CoreFavFolderInfo>> favFolderInfo({
    required Object? mediaId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#favFolderInfo, [], {#mediaId: mediaId}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i6.CoreFavFolderInfo>>.value(
                  _i5.dummyValue<_i4.LoadingState<_i6.CoreFavFolderInfo>>(
                    this,
                    Invocation.method(#favFolderInfo, [], {#mediaId: mediaId}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i6.CoreFavFolderInfo>>);

  @override
  _i3.Future<_i4.LoadingState<void>> deleteFolder({
    required String? mediaIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFolder, [], {#mediaIds: mediaIds}),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i5.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#deleteFolder, [], {#mediaIds: mediaIds}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> sortFav({
    required Object? mediaId,
    required String? sort,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sortFav, [], {#mediaId: mediaId, #sort: sort}),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i5.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#sortFav, [], {
                  #mediaId: mediaId,
                  #sort: sort,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> sortFavFolder({required String? sort}) =>
      (super.noSuchMethod(
            Invocation.method(#sortFavFolder, [], {#sort: sort}),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i5.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#sortFavFolder, [], {#sort: sort}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> cleanFav({required Object? mediaId}) =>
      (super.noSuchMethod(
            Invocation.method(#cleanFav, [], {#mediaId: mediaId}),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i5.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#cleanFav, [], {#mediaId: mediaId}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> copyOrMoveFav({
    required bool? isCopy,
    required bool? isFav,
    required dynamic srcMediaId,
    required dynamic tarMediaId,
    dynamic mid,
    required String? resources,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyOrMoveFav, [], {
              #isCopy: isCopy,
              #isFav: isFav,
              #srcMediaId: srcMediaId,
              #tarMediaId: tarMediaId,
              #mid: mid,
              #resources: resources,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i5.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#copyOrMoveFav, [], {
                  #isCopy: isCopy,
                  #isFav: isFav,
                  #srcMediaId: srcMediaId,
                  #tarMediaId: tarMediaId,
                  #mid: mid,
                  #resources: resources,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> communityAction({
    required Object? opusId,
    required Object? action,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#communityAction, [], {
              #opusId: opusId,
              #action: action,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i5.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#communityAction, [], {
                  #opusId: opusId,
                  #action: action,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);
}
