// Mocks generated by Mockito 5.4.6 from annotations
// in skf/test/repository/follow_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:skf/core/models/follow_data.dart' as _i5;
import 'package:skf/core/repository/follow_repository.dart' as _i2;
import 'package:skf/core/result/loading_state.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FollowRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFollowRepository extends _i1.Mock implements _i2.FollowRepository {
  MockFollowRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreFollowData>> followings({
    int? vmid,
    int? pn,
    int? ps = 20,
    String? orderType = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#followings, [], {
              #vmid: vmid,
              #pn: pn,
              #ps: ps,
              #orderType: orderType,
            }),
            returnValue: _i3.Future<_i4.LoadingState<_i5.CoreFollowData>>.value(
              _i6.dummyValue<_i4.LoadingState<_i5.CoreFollowData>>(
                this,
                Invocation.method(#followings, [], {
                  #vmid: vmid,
                  #pn: pn,
                  #ps: ps,
                  #orderType: orderType,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreFollowData>>);

  @override
  _i3.Future<_i4.LoadingState<void>> sortFollowTag({required String? tagids}) =>
      (super.noSuchMethod(
            Invocation.method(#sortFollowTag, [], {#tagids: tagids}),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#sortFollowTag, [], {#tagids: tagids}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);
}
