// Mocks generated by Mockito 5.4.6 from annotations
// in skf/test/repository/im_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:skf/core/models/im_types.dart' as _i5;
import 'package:skf/core/repository/im_repository.dart' as _i2;
import 'package:skf/core/result/loading_state.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ImRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockImRepository extends _i1.Mock implements _i2.ImRepository {
  MockImRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreImRspSendMsg>> sendMsg({
    required int? senderUid,
    required int? receiverId,
    required String? content,
    _i5.CoreImMsgType? msgType = _i5.CoreImMsgType.text,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMsg, [], {
              #senderUid: senderUid,
              #receiverId: receiverId,
              #content: content,
              #msgType: msgType,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreImRspSendMsg>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreImRspSendMsg>>(
                    this,
                    Invocation.method(#sendMsg, [], {
                      #senderUid: senderUid,
                      #receiverId: receiverId,
                      #content: content,
                      #msgType: msgType,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreImRspSendMsg>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreImRspShareList>> shareList({
    int? size = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#shareList, [], {#size: size}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreImRspShareList>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreImRspShareList>>(
                    this,
                    Invocation.method(#shareList, [], {#size: size}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreImRspShareList>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreImRspSessionMsg>> syncFetchSessionMsgs({
    required int? talkerId,
    int? endSeqno,
    int? beginSeqno,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#syncFetchSessionMsgs, [], {
              #talkerId: talkerId,
              #endSeqno: endSeqno,
              #beginSeqno: beginSeqno,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreImRspSessionMsg>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreImRspSessionMsg>>(
                    this,
                    Invocation.method(#syncFetchSessionMsgs, [], {
                      #talkerId: talkerId,
                      #endSeqno: endSeqno,
                      #beginSeqno: beginSeqno,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreImRspSessionMsg>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreImSessionMainReply>> sessionMain({
    Map<int, _i5.CoreImOffset>? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sessionMain, [], {#offset: offset}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreImSessionMainReply>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreImSessionMainReply>>(
                    this,
                    Invocation.method(#sessionMain, [], {#offset: offset}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreImSessionMainReply>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreImSessionSecondaryReply>>
  sessionSecondary({
    Map<int, _i5.CoreImOffset>? offset,
    _i5.CoreImSessionPageType? pageType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sessionSecondary, [], {
              #offset: offset,
              #pageType: pageType,
            }),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<_i5.CoreImSessionSecondaryReply>
                >.value(
                  _i6.dummyValue<
                    _i4.LoadingState<_i5.CoreImSessionSecondaryReply>
                  >(
                    this,
                    Invocation.method(#sessionSecondary, [], {
                      #offset: offset,
                      #pageType: pageType,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreImSessionSecondaryReply>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreImClearUnreadReply>> clearUnread({
    _i5.CoreImSessionPageType? pageType,
    _i5.CoreImSessionId? sessionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clearUnread, [], {
              #pageType: pageType,
              #sessionId: sessionId,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreImClearUnreadReply>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreImClearUnreadReply>>(
                    this,
                    Invocation.method(#clearUnread, [], {
                      #pageType: pageType,
                      #sessionId: sessionId,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreImClearUnreadReply>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreImSessionUpdateReply>> sessionUpdate({
    _i5.CoreImSessionPageType? pageType,
    _i5.CoreImSessionId? sessionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sessionUpdate, [], {
              #pageType: pageType,
              #sessionId: sessionId,
            }),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<_i5.CoreImSessionUpdateReply>
                >.value(
                  _i6.dummyValue<
                    _i4.LoadingState<_i5.CoreImSessionUpdateReply>
                  >(
                    this,
                    Invocation.method(#sessionUpdate, [], {
                      #pageType: pageType,
                      #sessionId: sessionId,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreImSessionUpdateReply>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreImPinSessionReply>> pinSession({
    _i5.CoreImSessionId? sessionId,
    int? topTimeMicros,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pinSession, [], {
              #sessionId: sessionId,
              #topTimeMicros: topTimeMicros,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreImPinSessionReply>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreImPinSessionReply>>(
                    this,
                    Invocation.method(#pinSession, [], {
                      #sessionId: sessionId,
                      #topTimeMicros: topTimeMicros,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreImPinSessionReply>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreImUnPinSessionReply>> unpinSession({
    _i5.CoreImSessionId? sessionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#unpinSession, [], {#sessionId: sessionId}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreImUnPinSessionReply>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreImUnPinSessionReply>>(
                    this,
                    Invocation.method(#unpinSession, [], {
                      #sessionId: sessionId,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreImUnPinSessionReply>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreImDeleteSessionListReply>>
  deleteSessionList({_i5.CoreImSessionPageType? pageType}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSessionList, [], {#pageType: pageType}),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<_i5.CoreImDeleteSessionListReply>
                >.value(
                  _i6.dummyValue<
                    _i4.LoadingState<_i5.CoreImDeleteSessionListReply>
                  >(
                    this,
                    Invocation.method(#deleteSessionList, [], {
                      #pageType: pageType,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreImDeleteSessionListReply>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreImGetImSettingsReply>> getImSettings({
    _i5.CoreImSettingType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getImSettings, [], {#type: type}),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<_i5.CoreImGetImSettingsReply>
                >.value(
                  _i6.dummyValue<
                    _i4.LoadingState<_i5.CoreImGetImSettingsReply>
                  >(this, Invocation.method(#getImSettings, [], {#type: type})),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreImGetImSettingsReply>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreImSetImSettingsReply>> setImSettings({
    Map<int, _i5.CoreImSetting>? settings,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setImSettings, [], {#settings: settings}),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<_i5.CoreImSetImSettingsReply>
                >.value(
                  _i6.dummyValue<
                    _i4.LoadingState<_i5.CoreImSetImSettingsReply>
                  >(
                    this,
                    Invocation.method(#setImSettings, [], {
                      #settings: settings,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreImSetImSettingsReply>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreImKeywordBlockingListReply>>
  keywordBlockingList() =>
      (super.noSuchMethod(
            Invocation.method(#keywordBlockingList, []),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<_i5.CoreImKeywordBlockingListReply>
                >.value(
                  _i6.dummyValue<
                    _i4.LoadingState<_i5.CoreImKeywordBlockingListReply>
                  >(this, Invocation.method(#keywordBlockingList, [])),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreImKeywordBlockingListReply>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreImKeywordBlockingAddReply>>
  keywordBlockingAdd(String? keyword) =>
      (super.noSuchMethod(
            Invocation.method(#keywordBlockingAdd, [keyword]),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<_i5.CoreImKeywordBlockingAddReply>
                >.value(
                  _i6.dummyValue<
                    _i4.LoadingState<_i5.CoreImKeywordBlockingAddReply>
                  >(this, Invocation.method(#keywordBlockingAdd, [keyword])),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreImKeywordBlockingAddReply>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreImKeywordBlockingDeleteReply>>
  keywordBlockingDelete(String? keyword) =>
      (super.noSuchMethod(
            Invocation.method(#keywordBlockingDelete, [keyword]),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<_i5.CoreImKeywordBlockingDeleteReply>
                >.value(
                  _i6.dummyValue<
                    _i4.LoadingState<_i5.CoreImKeywordBlockingDeleteReply>
                  >(this, Invocation.method(#keywordBlockingDelete, [keyword])),
                ),
          )
          as _i3.Future<
            _i4.LoadingState<_i5.CoreImKeywordBlockingDeleteReply>
          >);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreImRspTotalUnread>> getTotalUnread({
    int? unreadType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalUnread, [], {#unreadType: unreadType}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreImRspTotalUnread>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreImRspTotalUnread>>(
                    this,
                    Invocation.method(#getTotalUnread, [], {
                      #unreadType: unreadType,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreImRspTotalUnread>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreImSessionInfo>> sessionDetail({
    int? talkerId,
    int? sessionType,
    int? uid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sessionDetail, [], {
              #talkerId: talkerId,
              #sessionType: sessionType,
              #uid: uid,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreImSessionInfo>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreImSessionInfo>>(
                    this,
                    Invocation.method(#sessionDetail, [], {
                      #talkerId: talkerId,
                      #sessionType: sessionType,
                      #uid: uid,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreImSessionInfo>>);
}
