// Mocks generated by Mockito 5.4.6 from annotations
// in skf/test/repository/live_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:skf/core/models/live_enums.dart' as _i7;
import 'package:skf/core/models/live_types.dart' as _i6;
import 'package:skf/core/repository/live_repository.dart' as _i2;
import 'package:skf/core/result/loading_state.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LiveRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLiveRepository extends _i1.Mock implements _i2.LiveRepository {
  MockLiveRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.LoadingState<void>> sendLiveMsg({
    required Object? roomId,
    required Object? msg,
    Object? dmType,
    Object? emoticonOptions,
    int? replyMid = 0,
    String? replayDmid = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendLiveMsg, [], {
              #roomId: roomId,
              #msg: msg,
              #dmType: dmType,
              #emoticonOptions: emoticonOptions,
              #replyMid: replyMid,
              #replayDmid: replayDmid,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i5.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#sendLiveMsg, [], {
                  #roomId: roomId,
                  #msg: msg,
                  #dmType: dmType,
                  #emoticonOptions: emoticonOptions,
                  #replyMid: replyMid,
                  #replayDmid: replayDmid,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<_i6.CoreRoomPlayInfoData>> liveRoomInfo({
    required Object? roomId,
    Object? qn,
    bool? onlyAudio = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#liveRoomInfo, [], {
              #roomId: roomId,
              #qn: qn,
              #onlyAudio: onlyAudio,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i6.CoreRoomPlayInfoData>>.value(
                  _i5.dummyValue<_i4.LoadingState<_i6.CoreRoomPlayInfoData>>(
                    this,
                    Invocation.method(#liveRoomInfo, [], {
                      #roomId: roomId,
                      #qn: qn,
                      #onlyAudio: onlyAudio,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i6.CoreRoomPlayInfoData>>);

  @override
  _i3.Future<_i4.LoadingState<_i6.CoreRoomInfoH5Data>> liveRoomInfoH5({
    required Object? roomId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#liveRoomInfoH5, [], {#roomId: roomId}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i6.CoreRoomInfoH5Data>>.value(
                  _i5.dummyValue<_i4.LoadingState<_i6.CoreRoomInfoH5Data>>(
                    this,
                    Invocation.method(#liveRoomInfoH5, [], {#roomId: roomId}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i6.CoreRoomInfoH5Data>>);

  @override
  _i3.Future<_i4.LoadingState<List<_i6.CoreDanmakuMsg>?>> liveRoomDmPrefetch({
    required Object? roomId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#liveRoomDmPrefetch, [], {#roomId: roomId}),
            returnValue:
                _i3.Future<_i4.LoadingState<List<_i6.CoreDanmakuMsg>?>>.value(
                  _i5.dummyValue<_i4.LoadingState<List<_i6.CoreDanmakuMsg>?>>(
                    this,
                    Invocation.method(#liveRoomDmPrefetch, [], {
                      #roomId: roomId,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i6.CoreDanmakuMsg>?>>);

  @override
  _i3.Future<_i4.LoadingState<_i6.CoreLiveDmInfoData>> liveRoomGetDanmakuToken({
    required Object? roomId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#liveRoomGetDanmakuToken, [], {#roomId: roomId}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i6.CoreLiveDmInfoData>>.value(
                  _i5.dummyValue<_i4.LoadingState<_i6.CoreLiveDmInfoData>>(
                    this,
                    Invocation.method(#liveRoomGetDanmakuToken, [], {
                      #roomId: roomId,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i6.CoreLiveDmInfoData>>);

  @override
  _i3.Future<_i4.LoadingState<List<_i6.CoreLiveEmoteDatum>?>> getLiveEmoticons({
    required int? roomId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getLiveEmoticons, [], {#roomId: roomId}),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<List<_i6.CoreLiveEmoteDatum>?>
                >.value(
                  _i5.dummyValue<
                    _i4.LoadingState<List<_i6.CoreLiveEmoteDatum>?>
                  >(
                    this,
                    Invocation.method(#getLiveEmoticons, [], {#roomId: roomId}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i6.CoreLiveEmoteDatum>?>>);

  @override
  _i3.Future<_i4.LoadingState<_i6.CoreLiveIndexData>> liveFeedIndex({
    required int? pn,
    bool? moduleSelect = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#liveFeedIndex, [], {
              #pn: pn,
              #moduleSelect: moduleSelect,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i6.CoreLiveIndexData>>.value(
                  _i5.dummyValue<_i4.LoadingState<_i6.CoreLiveIndexData>>(
                    this,
                    Invocation.method(#liveFeedIndex, [], {
                      #pn: pn,
                      #moduleSelect: moduleSelect,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i6.CoreLiveIndexData>>);

  @override
  _i3.Future<_i4.LoadingState<_i6.CoreLiveFollowData>> liveFollow(int? page) =>
      (super.noSuchMethod(
            Invocation.method(#liveFollow, [page]),
            returnValue:
                _i3.Future<_i4.LoadingState<_i6.CoreLiveFollowData>>.value(
                  _i5.dummyValue<_i4.LoadingState<_i6.CoreLiveFollowData>>(
                    this,
                    Invocation.method(#liveFollow, [page]),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i6.CoreLiveFollowData>>);

  @override
  _i3.Future<_i4.LoadingState<_i6.CoreLiveSecondData>> liveSecondList({
    required int? pn,
    required Object? areaId,
    required Object? parentAreaId,
    String? sortType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#liveSecondList, [], {
              #pn: pn,
              #areaId: areaId,
              #parentAreaId: parentAreaId,
              #sortType: sortType,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i6.CoreLiveSecondData>>.value(
                  _i5.dummyValue<_i4.LoadingState<_i6.CoreLiveSecondData>>(
                    this,
                    Invocation.method(#liveSecondList, [], {
                      #pn: pn,
                      #areaId: areaId,
                      #parentAreaId: parentAreaId,
                      #sortType: sortType,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i6.CoreLiveSecondData>>);

  @override
  _i3.Future<_i4.LoadingState<List<_i6.CoreAreaList>?>> liveAreaList() =>
      (super.noSuchMethod(
            Invocation.method(#liveAreaList, []),
            returnValue:
                _i3.Future<_i4.LoadingState<List<_i6.CoreAreaList>?>>.value(
                  _i5.dummyValue<_i4.LoadingState<List<_i6.CoreAreaList>?>>(
                    this,
                    Invocation.method(#liveAreaList, []),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i6.CoreAreaList>?>>);

  @override
  _i3.Future<_i4.LoadingState<List<_i6.CoreAreaItem>>> getLiveFavTag() =>
      (super.noSuchMethod(
            Invocation.method(#getLiveFavTag, []),
            returnValue:
                _i3.Future<_i4.LoadingState<List<_i6.CoreAreaItem>>>.value(
                  _i5.dummyValue<_i4.LoadingState<List<_i6.CoreAreaItem>>>(
                    this,
                    Invocation.method(#getLiveFavTag, []),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i6.CoreAreaItem>>>);

  @override
  _i3.Future<_i4.LoadingState<void>> setLiveFavTag({required String? ids}) =>
      (super.noSuchMethod(
            Invocation.method(#setLiveFavTag, [], {#ids: ids}),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i5.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#setLiveFavTag, [], {#ids: ids}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<List<_i6.CoreAreaItem>?>> liveRoomAreaList({
    required Object? parentid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#liveRoomAreaList, [], {#parentid: parentid}),
            returnValue:
                _i3.Future<_i4.LoadingState<List<_i6.CoreAreaItem>?>>.value(
                  _i5.dummyValue<_i4.LoadingState<List<_i6.CoreAreaItem>?>>(
                    this,
                    Invocation.method(#liveRoomAreaList, [], {
                      #parentid: parentid,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i6.CoreAreaItem>?>>);

  @override
  _i3.Future<_i4.LoadingState<_i6.CoreLiveSearchData>> liveSearch({
    required int? page,
    required String? keyword,
    required _i7.CoreLiveSearchType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#liveSearch, [], {
              #page: page,
              #keyword: keyword,
              #type: type,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i6.CoreLiveSearchData>>.value(
                  _i5.dummyValue<_i4.LoadingState<_i6.CoreLiveSearchData>>(
                    this,
                    Invocation.method(#liveSearch, [], {
                      #page: page,
                      #keyword: keyword,
                      #type: type,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i6.CoreLiveSearchData>>);

  @override
  _i3.Future<_i4.LoadingState<_i6.CoreShieldInfo?>> getLiveInfoByUser(
    Object? roomId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLiveInfoByUser, [roomId]),
            returnValue:
                _i3.Future<_i4.LoadingState<_i6.CoreShieldInfo?>>.value(
                  _i5.dummyValue<_i4.LoadingState<_i6.CoreShieldInfo?>>(
                    this,
                    Invocation.method(#getLiveInfoByUser, [roomId]),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i6.CoreShieldInfo?>>);

  @override
  _i3.Future<_i4.LoadingState<void>> liveSetSilent({
    required String? type,
    required int? level,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#liveSetSilent, [], {#type: type, #level: level}),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i5.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#liveSetSilent, [], {
                  #type: type,
                  #level: level,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> addShieldKeyword({
    required String? keyword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addShieldKeyword, [], {#keyword: keyword}),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i5.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#addShieldKeyword, [], {#keyword: keyword}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> delShieldKeyword({
    required String? keyword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delShieldKeyword, [], {#keyword: keyword}),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i5.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#delShieldKeyword, [], {#keyword: keyword}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<_i6.CoreShieldUserList>> liveShieldUser({
    required Object? uid,
    required Object? roomid,
    required int? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#liveShieldUser, [], {
              #uid: uid,
              #roomid: roomid,
              #type: type,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i6.CoreShieldUserList>>.value(
                  _i5.dummyValue<_i4.LoadingState<_i6.CoreShieldUserList>>(
                    this,
                    Invocation.method(#liveShieldUser, [], {
                      #uid: uid,
                      #roomid: roomid,
                      #type: type,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i6.CoreShieldUserList>>);

  @override
  _i3.Future<_i4.LoadingState<void>> liveLikeReport({
    required int? clickTime,
    required Object? roomId,
    required Object? uid,
    Object? anchorId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#liveLikeReport, [], {
              #clickTime: clickTime,
              #roomId: roomId,
              #uid: uid,
              #anchorId: anchorId,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i5.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#liveLikeReport, [], {
                  #clickTime: clickTime,
                  #roomId: roomId,
                  #uid: uid,
                  #anchorId: anchorId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<_i6.CoreSuperChatData>> superChatMsg(
    Object? roomId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#superChatMsg, [roomId]),
            returnValue:
                _i3.Future<_i4.LoadingState<_i6.CoreSuperChatData>>.value(
                  _i5.dummyValue<_i4.LoadingState<_i6.CoreSuperChatData>>(
                    this,
                    Invocation.method(#superChatMsg, [roomId]),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i6.CoreSuperChatData>>);

  @override
  _i3.Future<_i4.LoadingState<void>> liveDmReport({
    required int? roomId,
    required Object? mid,
    required String? msg,
    required String? reason,
    required int? reasonId,
    required int? dmType,
    required Object? idStr,
    required Object? ts,
    required Object? sign,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#liveDmReport, [], {
              #roomId: roomId,
              #mid: mid,
              #msg: msg,
              #reason: reason,
              #reasonId: reasonId,
              #dmType: dmType,
              #idStr: idStr,
              #ts: ts,
              #sign: sign,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i5.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#liveDmReport, [], {
                  #roomId: roomId,
                  #mid: mid,
                  #msg: msg,
                  #reason: reason,
                  #reasonId: reasonId,
                  #dmType: dmType,
                  #idStr: idStr,
                  #ts: ts,
                  #sign: sign,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<_i6.CoreLiveContributionRankData>>
  liveContributionRank({
    required Object? ruid,
    required Object? roomId,
    required int? page,
    required _i7.CoreLiveContributionRankType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#liveContributionRank, [], {
              #ruid: ruid,
              #roomId: roomId,
              #page: page,
              #type: type,
            }),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<_i6.CoreLiveContributionRankData>
                >.value(
                  _i5.dummyValue<
                    _i4.LoadingState<_i6.CoreLiveContributionRankData>
                  >(
                    this,
                    Invocation.method(#liveContributionRank, [], {
                      #ruid: ruid,
                      #roomId: roomId,
                      #page: page,
                      #type: type,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i6.CoreLiveContributionRankData>>);

  @override
  _i3.Future<_i4.LoadingState<void>> superChatReport({
    required int? id,
    required Object? roomId,
    required Object? uid,
    required String? msg,
    required String? reason,
    required int? ts,
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#superChatReport, [], {
              #id: id,
              #roomId: roomId,
              #uid: uid,
              #msg: msg,
              #reason: reason,
              #ts: ts,
              #token: token,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i5.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#superChatReport, [], {
                  #id: id,
                  #roomId: roomId,
                  #uid: uid,
                  #msg: msg,
                  #reason: reason,
                  #ts: ts,
                  #token: token,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<_i6.CoreMedalWallData>> liveMedalWall({
    required Object? mid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#liveMedalWall, [], {#mid: mid}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i6.CoreMedalWallData>>.value(
                  _i5.dummyValue<_i4.LoadingState<_i6.CoreMedalWallData>>(
                    this,
                    Invocation.method(#liveMedalWall, [], {#mid: mid}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i6.CoreMedalWallData>>);
}
