// Mocks generated by Mockito 5.4.6 from annotations
// in skf/test/repository/member_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:skf/core/models/dynamics_types.dart' as _i7;
import 'package:skf/core/models/follow_data.dart' as _i8;
import 'package:skf/core/models/member_types.dart' as _i5;
import 'package:skf/core/models/space_types.dart' as _i9;
import 'package:skf/core/repository/member_repository.dart' as _i2;
import 'package:skf/core/result/loading_state.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [MemberRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMemberRepository extends _i1.Mock implements _i2.MemberRepository {
  MockMemberRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> reportMember(int? mid, {String? reason, int? reasonV2}) =>
      (super.noSuchMethod(
            Invocation.method(
              #reportMember,
              [mid],
              {#reason: reason, #reasonV2: reasonV2},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreSpaceArticleData>> spaceArticle({
    required int? mid,
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#spaceArticle, [], {#mid: mid, #page: page}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreSpaceArticleData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreSpaceArticleData>>(
                    this,
                    Invocation.method(#spaceArticle, [], {
                      #mid: mid,
                      #page: page,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreSpaceArticleData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreSpaceSsData>> seasonSeriesList({
    required int? mid,
    required int? pn,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#seasonSeriesList, [], {#mid: mid, #pn: pn}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreSpaceSsData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreSpaceSsData>>(
                    this,
                    Invocation.method(#seasonSeriesList, [], {
                      #mid: mid,
                      #pn: pn,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreSpaceSsData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreSpaceArchiveData>> spaceArchive({
    required _i5.CoreContributeType? type,
    required int? mid,
    String? aid,
    _i5.CoreArchiveOrderTypeApp? order,
    _i5.CoreArchiveSortTypeApp? sort,
    int? pn,
    int? next,
    int? seasonId,
    String? seriesId,
    bool? includeCursor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#spaceArchive, [], {
              #type: type,
              #mid: mid,
              #aid: aid,
              #order: order,
              #sort: sort,
              #pn: pn,
              #next: next,
              #seasonId: seasonId,
              #seriesId: seriesId,
              #includeCursor: includeCursor,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreSpaceArchiveData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreSpaceArchiveData>>(
                    this,
                    Invocation.method(#spaceArchive, [], {
                      #type: type,
                      #mid: mid,
                      #aid: aid,
                      #order: order,
                      #sort: sort,
                      #pn: pn,
                      #next: next,
                      #seasonId: seasonId,
                      #seriesId: seriesId,
                      #includeCursor: includeCursor,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreSpaceArchiveData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreSpaceAudioData>> spaceAudio({
    required int? page,
    required dynamic mid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#spaceAudio, [], {#page: page, #mid: mid}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreSpaceAudioData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreSpaceAudioData>>(
                    this,
                    Invocation.method(#spaceAudio, [], {
                      #page: page,
                      #mid: mid,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreSpaceAudioData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreSpaceCheeseData>> spaceCheese({
    required int? page,
    required dynamic mid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#spaceCheese, [], {#page: page, #mid: mid}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreSpaceCheeseData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreSpaceCheeseData>>(
                    this,
                    Invocation.method(#spaceCheese, [], {
                      #page: page,
                      #mid: mid,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreSpaceCheeseData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreSpaceData>> space({
    int? mid,
    int? fromViewAid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#space, [], {
              #mid: mid,
              #fromViewAid: fromViewAid,
            }),
            returnValue: _i3.Future<_i4.LoadingState<_i5.CoreSpaceData>>.value(
              _i6.dummyValue<_i4.LoadingState<_i5.CoreSpaceData>>(
                this,
                Invocation.method(#space, [], {
                  #mid: mid,
                  #fromViewAid: fromViewAid,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreSpaceData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreMemberInfoModel>> memberInfo({
    required int? mid,
    String? token = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#memberInfo, [], {#mid: mid, #token: token}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreMemberInfoModel>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreMemberInfoModel>>(
                    this,
                    Invocation.method(#memberInfo, [], {
                      #mid: mid,
                      #token: token,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreMemberInfoModel>>);

  @override
  _i3.Future<_i4.LoadingState<Map<dynamic, dynamic>>> memberStat({int? mid}) =>
      (super.noSuchMethod(
            Invocation.method(#memberStat, [], {#mid: mid}),
            returnValue:
                _i3.Future<_i4.LoadingState<Map<dynamic, dynamic>>>.value(
                  _i6.dummyValue<_i4.LoadingState<Map<dynamic, dynamic>>>(
                    this,
                    Invocation.method(#memberStat, [], {#mid: mid}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<Map<dynamic, dynamic>>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreMemberCardInfoData>> memberCardInfo({
    int? mid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#memberCardInfo, [], {#mid: mid}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreMemberCardInfoData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreMemberCardInfoData>>(
                    this,
                    Invocation.method(#memberCardInfo, [], {#mid: mid}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreMemberCardInfoData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreSearchArchiveData>> searchArchive({
    required Object? mid,
    int? tid = 0,
    int? ps = 30,
    required int? pn,
    String? keyword,
    String? specialType,
    _i5.CoreArchiveOrderTypeWeb? order = _i5.CoreArchiveOrderTypeWeb.pubdate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchArchive, [], {
              #mid: mid,
              #tid: tid,
              #ps: ps,
              #pn: pn,
              #keyword: keyword,
              #specialType: specialType,
              #order: order,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreSearchArchiveData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreSearchArchiveData>>(
                    this,
                    Invocation.method(#searchArchive, [], {
                      #mid: mid,
                      #tid: tid,
                      #ps: ps,
                      #pn: pn,
                      #keyword: keyword,
                      #specialType: specialType,
                      #order: order,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreSearchArchiveData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreSeasonWebData>> seasonSeriesWeb({
    required _i5.CoreWebSsType? type,
    required Object? mid,
    required Object? id,
    int? ps = 30,
    required int? pn,
    _i5.CoreArchiveSortTypeApp? sort = _i5.CoreArchiveSortTypeApp.desc,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#seasonSeriesWeb, [], {
              #type: type,
              #mid: mid,
              #id: id,
              #ps: ps,
              #pn: pn,
              #sort: sort,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreSeasonWebData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreSeasonWebData>>(
                    this,
                    Invocation.method(#seasonSeriesWeb, [], {
                      #type: type,
                      #mid: mid,
                      #id: id,
                      #ps: ps,
                      #pn: pn,
                      #sort: sort,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreSeasonWebData>>);

  @override
  _i3.Future<_i4.LoadingState<_i7.CoreDynamicsDataModel>> memberDynamic({
    String? offset,
    required int? mid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#memberDynamic, [], {#offset: offset, #mid: mid}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i7.CoreDynamicsDataModel>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i7.CoreDynamicsDataModel>>(
                    this,
                    Invocation.method(#memberDynamic, [], {
                      #offset: offset,
                      #mid: mid,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i7.CoreDynamicsDataModel>>);

  @override
  _i3.Future<_i4.LoadingState<_i7.CoreDynamicsDataModel>> dynSearch({
    required int? pn,
    required dynamic mid,
    required String? offset,
    required String? keyword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#dynSearch, [], {
              #pn: pn,
              #mid: mid,
              #offset: offset,
              #keyword: keyword,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i7.CoreDynamicsDataModel>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i7.CoreDynamicsDataModel>>(
                    this,
                    Invocation.method(#dynSearch, [], {
                      #pn: pn,
                      #mid: mid,
                      #offset: offset,
                      #keyword: keyword,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i7.CoreDynamicsDataModel>>);

  @override
  _i3.Future<_i4.LoadingState<List<_i5.CoreMemberTagItemModel>>>
  followUpTags() =>
      (super.noSuchMethod(
            Invocation.method(#followUpTags, []),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<List<_i5.CoreMemberTagItemModel>>
                >.value(
                  _i6.dummyValue<
                    _i4.LoadingState<List<_i5.CoreMemberTagItemModel>>
                  >(this, Invocation.method(#followUpTags, [])),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i5.CoreMemberTagItemModel>>>);

  @override
  _i3.Future<_i4.LoadingState<void>> specialAction({
    int? fid,
    bool? isAdd = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#specialAction, [], {#fid: fid, #isAdd: isAdd}),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#specialAction, [], {
                  #fid: fid,
                  #isAdd: isAdd,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> addUsers(String? fids, String? tagids) =>
      (super.noSuchMethod(
            Invocation.method(#addUsers, [fids, tagids]),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#addUsers, [fids, tagids]),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<_i8.CoreFollowData>> followUpGroup({
    int? mid,
    int? tagid,
    int? pn,
    int? ps = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#followUpGroup, [], {
              #mid: mid,
              #tagid: tagid,
              #pn: pn,
              #ps: ps,
            }),
            returnValue: _i3.Future<_i4.LoadingState<_i8.CoreFollowData>>.value(
              _i6.dummyValue<_i4.LoadingState<_i8.CoreFollowData>>(
                this,
                Invocation.method(#followUpGroup, [], {
                  #mid: mid,
                  #tagid: tagid,
                  #pn: pn,
                  #ps: ps,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<_i8.CoreFollowData>>);

  @override
  _i3.Future<_i4.LoadingState<int>> createFollowTag(String? tagName) =>
      (super.noSuchMethod(
            Invocation.method(#createFollowTag, [tagName]),
            returnValue: _i3.Future<_i4.LoadingState<int>>.value(
              _i6.dummyValue<_i4.LoadingState<int>>(
                this,
                Invocation.method(#createFollowTag, [tagName]),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<int>>);

  @override
  _i3.Future<_i4.LoadingState<void>> updateFollowTag(
    Object? tagid,
    Object? name,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateFollowTag, [tagid, name]),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#updateFollowTag, [tagid, name]),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> delFollowTag(Object? tagid) =>
      (super.noSuchMethod(
            Invocation.method(#delFollowTag, [tagid]),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#delFollowTag, [tagid]),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<List<_i5.CoreMemberTagItemModel>?>>
  getTopVideo() =>
      (super.noSuchMethod(
            Invocation.method(#getTopVideo, []),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<List<_i5.CoreMemberTagItemModel>?>
                >.value(
                  _i6.dummyValue<
                    _i4.LoadingState<List<_i5.CoreMemberTagItemModel>?>
                  >(this, Invocation.method(#getTopVideo, [])),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i5.CoreMemberTagItemModel>?>>);

  @override
  _i3.Future<_i4.LoadingState<Map<dynamic, dynamic>>> memberView({
    required int? mid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#memberView, [], {#mid: mid}),
            returnValue:
                _i3.Future<_i4.LoadingState<Map<dynamic, dynamic>>>.value(
                  _i6.dummyValue<_i4.LoadingState<Map<dynamic, dynamic>>>(
                    this,
                    Invocation.method(#memberView, [], {#mid: mid}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<Map<dynamic, dynamic>>>);

  @override
  _i3.Future<_i4.LoadingState<_i8.CoreFollowData>> getfollowSearch({
    required int? mid,
    required int? ps,
    required int? pn,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getfollowSearch, [], {
              #mid: mid,
              #ps: ps,
              #pn: pn,
              #name: name,
            }),
            returnValue: _i3.Future<_i4.LoadingState<_i8.CoreFollowData>>.value(
              _i6.dummyValue<_i4.LoadingState<_i8.CoreFollowData>>(
                this,
                Invocation.method(#getfollowSearch, [], {
                  #mid: mid,
                  #ps: ps,
                  #pn: pn,
                  #name: name,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<_i8.CoreFollowData>>);

  @override
  _i3.Future<_i4.LoadingState<_i9.CoreOpusSpaceFlowResp>> spaceOpus({
    required int? hostMid,
    required int? page,
    String? offset = '',
    String? type = 'all',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#spaceOpus, [], {
              #hostMid: hostMid,
              #page: page,
              #offset: offset,
              #type: type,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i9.CoreOpusSpaceFlowResp>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i9.CoreOpusSpaceFlowResp>>(
                    this,
                    Invocation.method(#spaceOpus, [], {
                      #hostMid: hostMid,
                      #page: page,
                      #offset: offset,
                      #type: type,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i9.CoreOpusSpaceFlowResp>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreUpowerRankData>> upowerRank({
    required Object? upMid,
    required int? page,
    int? privilegeType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upowerRank, [], {
              #upMid: upMid,
              #page: page,
              #privilegeType: privilegeType,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreUpowerRankData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreUpowerRankData>>(
                    this,
                    Invocation.method(#upowerRank, [], {
                      #upMid: upMid,
                      #page: page,
                      #privilegeType: privilegeType,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreUpowerRankData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreCoinLikeArcData>> coinArc({
    required int? mid,
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#coinArc, [], {#mid: mid, #page: page}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreCoinLikeArcData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreCoinLikeArcData>>(
                    this,
                    Invocation.method(#coinArc, [], {#mid: mid, #page: page}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreCoinLikeArcData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreCoinLikeArcData>> likeArc({
    required int? mid,
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#likeArc, [], {#mid: mid, #page: page}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreCoinLikeArcData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreCoinLikeArcData>>(
                    this,
                    Invocation.method(#likeArc, [], {#mid: mid, #page: page}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreCoinLikeArcData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreSpaceShopData>> spaceShop({
    required int? mid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#spaceShop, [], {#mid: mid}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreSpaceShopData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreSpaceShopData>>(
                    this,
                    Invocation.method(#spaceShop, [], {#mid: mid}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreSpaceShopData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreMemberGuardData>> memberGuard({
    required Object? ruid,
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#memberGuard, [], {#ruid: ruid, #page: page}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreMemberGuardData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreMemberGuardData>>(
                    this,
                    Invocation.method(#memberGuard, [], {
                      #ruid: ruid,
                      #page: page,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreMemberGuardData>>);
}
