// Mocks generated by Mockito 5.4.6 from annotations
// in skf/test/repository/msg_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dio/dio.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:skf/core/models/msg_types.dart' as _i5;
import 'package:skf/core/repository/msg_repository.dart' as _i2;
import 'package:skf/core/result/loading_state.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [MsgRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMsgRepository extends _i1.Mock implements _i2.MsgRepository {
  MockMsgRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreMsgReplyData>> msgFeedReplyMe({
    int? cursor,
    int? cursorTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#msgFeedReplyMe, [], {
              #cursor: cursor,
              #cursorTime: cursorTime,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreMsgReplyData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreMsgReplyData>>(
                    this,
                    Invocation.method(#msgFeedReplyMe, [], {
                      #cursor: cursor,
                      #cursorTime: cursorTime,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreMsgReplyData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreMsgAtData>> msgFeedAtMe({
    int? cursor,
    int? cursorTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#msgFeedAtMe, [], {
              #cursor: cursor,
              #cursorTime: cursorTime,
            }),
            returnValue: _i3.Future<_i4.LoadingState<_i5.CoreMsgAtData>>.value(
              _i6.dummyValue<_i4.LoadingState<_i5.CoreMsgAtData>>(
                this,
                Invocation.method(#msgFeedAtMe, [], {
                  #cursor: cursor,
                  #cursorTime: cursorTime,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreMsgAtData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreMsgLikeData>> msgFeedLikeMe({
    int? cursor,
    int? cursorTime,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#msgFeedLikeMe, [], {
              #cursor: cursor,
              #cursorTime: cursorTime,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreMsgLikeData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreMsgLikeData>>(
                    this,
                    Invocation.method(#msgFeedLikeMe, [], {
                      #cursor: cursor,
                      #cursorTime: cursorTime,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreMsgLikeData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreMsgLikeDetailData>> msgLikeDetail({
    required Object? cardId,
    required int? pn,
    Object? lastMid = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#msgLikeDetail, [], {
              #cardId: cardId,
              #pn: pn,
              #lastMid: lastMid,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreMsgLikeDetailData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreMsgLikeDetailData>>(
                    this,
                    Invocation.method(#msgLikeDetail, [], {
                      #cardId: cardId,
                      #pn: pn,
                      #lastMid: lastMid,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreMsgLikeDetailData>>);

  @override
  _i3.Future<_i4.LoadingState<List<_i5.CoreMsgSysItem>?>> msgFeedNotify({
    int? cursor,
    int? pageSize = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#msgFeedNotify, [], {
              #cursor: cursor,
              #pageSize: pageSize,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<List<_i5.CoreMsgSysItem>?>>.value(
                  _i6.dummyValue<_i4.LoadingState<List<_i5.CoreMsgSysItem>?>>(
                    this,
                    Invocation.method(#msgFeedNotify, [], {
                      #cursor: cursor,
                      #pageSize: pageSize,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i5.CoreMsgSysItem>?>>);

  @override
  _i3.Future<_i4.LoadingState<void>> msgSysUpdateCursor(int? cursor) =>
      (super.noSuchMethod(
            Invocation.method(#msgSysUpdateCursor, [cursor]),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#msgSysUpdateCursor, [cursor]),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<Map<dynamic, dynamic>>> uploadImage({
    required dynamic path,
    required String? bucket,
    required String? dir,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImage, [], {
              #path: path,
              #bucket: bucket,
              #dir: dir,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<Map<dynamic, dynamic>>>.value(
                  _i6.dummyValue<_i4.LoadingState<Map<dynamic, dynamic>>>(
                    this,
                    Invocation.method(#uploadImage, [], {
                      #path: path,
                      #bucket: bucket,
                      #dir: dir,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<Map<dynamic, dynamic>>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreUploadBfsResData>> uploadBfs({
    required String? path,
    String? category,
    String? biz,
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadBfs, [], {
              #path: path,
              #category: category,
              #biz: biz,
              #cancelToken: cancelToken,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreUploadBfsResData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreUploadBfsResData>>(
                    this,
                    Invocation.method(#uploadBfs, [], {
                      #path: path,
                      #category: category,
                      #biz: biz,
                      #cancelToken: cancelToken,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreUploadBfsResData>>);

  @override
  _i3.Future<_i4.LoadingState<void>> createTextDynamic(Object? content) =>
      (super.noSuchMethod(
            Invocation.method(#createTextDynamic, [content]),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#createTextDynamic, [content]),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> removeDynamic({
    required Object? dynIdStr,
    Object? dynType,
    Object? ridStr,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeDynamic, [], {
              #dynIdStr: dynIdStr,
              #dynType: dynType,
              #ridStr: ridStr,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#removeDynamic, [], {
                  #dynIdStr: dynIdStr,
                  #dynType: dynType,
                  #ridStr: ridStr,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> removeMsg(Object? talkerId) =>
      (super.noSuchMethod(
            Invocation.method(#removeMsg, [talkerId]),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#removeMsg, [talkerId]),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> delMsgfeed(int? tp, dynamic id) =>
      (super.noSuchMethod(
            Invocation.method(#delMsgfeed, [tp, id]),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#delMsgfeed, [tp, id]),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> delSysMsg(Object? id) =>
      (super.noSuchMethod(
            Invocation.method(#delSysMsg, [id]),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#delSysMsg, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> setTop({
    required Object? talkerId,
    required int? opType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setTop, [], {
              #talkerId: talkerId,
              #opType: opType,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#setTop, [], {
                  #talkerId: talkerId,
                  #opType: opType,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> ackSessionMsg({
    required int? talkerId,
    required int? ackSeqno,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#ackSessionMsg, [], {
              #talkerId: talkerId,
              #ackSeqno: ackSeqno,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#ackSessionMsg, [], {
                  #talkerId: talkerId,
                  #ackSeqno: ackSeqno,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> msgSetNotice({
    required Object? id,
    required int? noticeState,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#msgSetNotice, [], {
              #id: id,
              #noticeState: noticeState,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#msgSetNotice, [], {
                  #id: id,
                  #noticeState: noticeState,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> setMsgDnd({
    required Object? uid,
    required int? setting,
    required dynamic dndUid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setMsgDnd, [], {
              #uid: uid,
              #setting: setting,
              #dndUid: dndUid,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#setMsgDnd, [], {
                  #uid: uid,
                  #setting: setting,
                  #dndUid: dndUid,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> setPushSs({
    required int? setting,
    required dynamic talkerUid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setPushSs, [], {
              #setting: setting,
              #talkerUid: talkerUid,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#setPushSs, [], {
                  #setting: setting,
                  #talkerUid: talkerUid,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<List<_i5.CoreImUserInfosData>?>> imUserInfos({
    required String? uids,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#imUserInfos, [], {#uids: uids}),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<List<_i5.CoreImUserInfosData>?>
                >.value(
                  _i6.dummyValue<
                    _i4.LoadingState<List<_i5.CoreImUserInfosData>?>
                  >(this, Invocation.method(#imUserInfos, [], {#uids: uids})),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i5.CoreImUserInfosData>?>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreSessionSsData>> getSessionSs({
    required Object? talkerUid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSessionSs, [], {#talkerUid: talkerUid}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreSessionSsData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreSessionSsData>>(
                    this,
                    Invocation.method(#getSessionSs, [], {
                      #talkerUid: talkerUid,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreSessionSsData>>);

  @override
  _i3.Future<_i4.LoadingState<List<_i5.CoreUidSetting>?>> getMsgDnd({
    required Object? uidsStr,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMsgDnd, [], {#uidsStr: uidsStr}),
            returnValue:
                _i3.Future<_i4.LoadingState<List<_i5.CoreUidSetting>?>>.value(
                  _i6.dummyValue<_i4.LoadingState<List<_i5.CoreUidSetting>?>>(
                    this,
                    Invocation.method(#getMsgDnd, [], {#uidsStr: uidsStr}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i5.CoreUidSetting>?>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreSingleUnreadData>> msgUnread() =>
      (super.noSuchMethod(
            Invocation.method(#msgUnread, []),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreSingleUnreadData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreSingleUnreadData>>(
                    this,
                    Invocation.method(#msgUnread, []),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreSingleUnreadData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreMsgFeedUnreadData>> msgFeedUnread() =>
      (super.noSuchMethod(
            Invocation.method(#msgFeedUnread, []),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreMsgFeedUnreadData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreMsgFeedUnreadData>>(
                    this,
                    Invocation.method(#msgFeedUnread, []),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreMsgFeedUnreadData>>);

  @override
  _i3.Future<_i4.LoadingState<void>> imMsgReport({
    required int? accusedUid,
    required int? reasonType,
    required String? reasonDesc,
    required Map<dynamic, dynamic>? comment,
    required Map<dynamic, dynamic>? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#imMsgReport, [], {
              #accusedUid: accusedUid,
              #reasonType: reasonType,
              #reasonDesc: reasonDesc,
              #comment: comment,
              #extra: extra,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#imMsgReport, [], {
                  #accusedUid: accusedUid,
                  #reasonType: reasonType,
                  #reasonDesc: reasonDesc,
                  #comment: comment,
                  #extra: extra,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);
}
