// Mocks generated by Mockito 5.4.6 from annotations
// in skf/test/repository/music_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:skf/core/models/music_types.dart' as _i5;
import 'package:skf/core/repository/music_repository.dart' as _i2;
import 'package:skf/core/result/loading_state.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [MusicRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMusicRepository extends _i1.Mock implements _i2.MusicRepository {
  MockMusicRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreMusicDetail>> bgmDetail(
    String? musicId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#bgmDetail, [musicId]),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreMusicDetail>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreMusicDetail>>(
                    this,
                    Invocation.method(#bgmDetail, [musicId]),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreMusicDetail>>);

  @override
  _i3.Future<_i4.LoadingState<void>> wishUpdate(
    String? musicId,
    bool? hasLike,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#wishUpdate, [musicId, hasLike]),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#wishUpdate, [musicId, hasLike]),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<List<_i5.CoreBgmRecommend>?>> bgmRecommend(
    String? musicId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#bgmRecommend, [musicId]),
            returnValue:
                _i3.Future<_i4.LoadingState<List<_i5.CoreBgmRecommend>?>>.value(
                  _i6.dummyValue<_i4.LoadingState<List<_i5.CoreBgmRecommend>?>>(
                    this,
                    Invocation.method(#bgmRecommend, [musicId]),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i5.CoreBgmRecommend>?>>);
}
