// Mocks generated by Mockito 5.4.6 from annotations
// in skf/test/repository/pgc_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:skf/core/models/pgc_types.dart' as _i5;
import 'package:skf/core/repository/pgc_repository.dart' as _i2;
import 'package:skf/core/result/loading_state.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PgcRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPgcRepository extends _i1.Mock implements _i2.PgcRepository {
  MockPgcRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.LoadingState<_i5.CorePgcIndexResult>> pgcIndexResult({
    required int? page,
    required Map<String, dynamic>? params,
    dynamic seasonType,
    dynamic type,
    dynamic indexType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pgcIndexResult, [], {
              #page: page,
              #params: params,
              #seasonType: seasonType,
              #type: type,
              #indexType: indexType,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CorePgcIndexResult>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CorePgcIndexResult>>(
                    this,
                    Invocation.method(#pgcIndexResult, [], {
                      #page: page,
                      #params: params,
                      #seasonType: seasonType,
                      #type: type,
                      #indexType: indexType,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CorePgcIndexResult>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CorePgcIndexConditionData>>
  pgcIndexCondition({
    Object? seasonType,
    required Object? type,
    Object? indexType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pgcIndexCondition, [], {
              #seasonType: seasonType,
              #type: type,
              #indexType: indexType,
            }),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<_i5.CorePgcIndexConditionData>
                >.value(
                  _i6.dummyValue<
                    _i4.LoadingState<_i5.CorePgcIndexConditionData>
                  >(
                    this,
                    Invocation.method(#pgcIndexCondition, [], {
                      #seasonType: seasonType,
                      #type: type,
                      #indexType: indexType,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CorePgcIndexConditionData>>);

  @override
  _i3.Future<_i4.LoadingState<List<_i5.CorePgcIndexItem>?>> pgcIndex({
    int? page,
    int? indexType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pgcIndex, [], {
              #page: page,
              #indexType: indexType,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<List<_i5.CorePgcIndexItem>?>>.value(
                  _i6.dummyValue<_i4.LoadingState<List<_i5.CorePgcIndexItem>?>>(
                    this,
                    Invocation.method(#pgcIndex, [], {
                      #page: page,
                      #indexType: indexType,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i5.CorePgcIndexItem>?>>);

  @override
  _i3.Future<_i4.LoadingState<List<_i5.CoreTimelineResult>?>> pgcTimeline({
    int? types = 1,
    required int? before,
    required int? after,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pgcTimeline, [], {
              #types: types,
              #before: before,
              #after: after,
            }),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<List<_i5.CoreTimelineResult>?>
                >.value(
                  _i6.dummyValue<
                    _i4.LoadingState<List<_i5.CoreTimelineResult>?>
                  >(
                    this,
                    Invocation.method(#pgcTimeline, [], {
                      #types: types,
                      #before: before,
                      #after: after,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i5.CoreTimelineResult>?>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CorePgcReviewData>> pgcReview({
    required _i5.CorePgcReviewType? type,
    required dynamic mediaId,
    int? sort = 0,
    String? next,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pgcReview, [], {
              #type: type,
              #mediaId: mediaId,
              #sort: sort,
              #next: next,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CorePgcReviewData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CorePgcReviewData>>(
                    this,
                    Invocation.method(#pgcReview, [], {
                      #type: type,
                      #mediaId: mediaId,
                      #sort: sort,
                      #next: next,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CorePgcReviewData>>);

  @override
  _i3.Future<_i4.LoadingState<void>> pgcReviewLike({
    required Object? mediaId,
    required Object? reviewId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pgcReviewLike, [], {
              #mediaId: mediaId,
              #reviewId: reviewId,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#pgcReviewLike, [], {
                  #mediaId: mediaId,
                  #reviewId: reviewId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> pgcReviewDislike({
    required Object? mediaId,
    required Object? reviewId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pgcReviewDislike, [], {
              #mediaId: mediaId,
              #reviewId: reviewId,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#pgcReviewDislike, [], {
                  #mediaId: mediaId,
                  #reviewId: reviewId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> pgcReviewPost({
    required Object? mediaId,
    required int? score,
    required String? content,
    bool? shareFeed = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pgcReviewPost, [], {
              #mediaId: mediaId,
              #score: score,
              #content: content,
              #shareFeed: shareFeed,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#pgcReviewPost, [], {
                  #mediaId: mediaId,
                  #score: score,
                  #content: content,
                  #shareFeed: shareFeed,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> pgcReviewMod({
    required Object? mediaId,
    required int? score,
    required String? content,
    required dynamic reviewId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pgcReviewMod, [], {
              #mediaId: mediaId,
              #score: score,
              #content: content,
              #reviewId: reviewId,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#pgcReviewMod, [], {
                  #mediaId: mediaId,
                  #score: score,
                  #content: content,
                  #reviewId: reviewId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> pgcReviewDel({
    required Object? mediaId,
    required Object? reviewId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pgcReviewDel, [], {
              #mediaId: mediaId,
              #reviewId: reviewId,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#pgcReviewDel, [], {
                  #mediaId: mediaId,
                  #reviewId: reviewId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<Map<dynamic, dynamic>>> seasonStatus(
    Object? seasonId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#seasonStatus, [seasonId]),
            returnValue:
                _i3.Future<_i4.LoadingState<Map<dynamic, dynamic>>>.value(
                  _i6.dummyValue<_i4.LoadingState<Map<dynamic, dynamic>>>(
                    this,
                    Invocation.method(#seasonStatus, [seasonId]),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<Map<dynamic, dynamic>>>);
}
