// Mocks generated by Mockito 5.4.6 from annotations
// in skf/test/repository/reply_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:skf/core/models/reply_types.dart' as _i5;
import 'package:skf/core/repository/reply_repository.dart' as _i2;
import 'package:skf/core/result/loading_state.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ReplyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReplyRepository extends _i1.Mock implements _i2.ReplyRepository {
  MockReplyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreMainListReply>> mainList({
    int? type = 1,
    required int? oid,
    required _i5.CoreMode? mode,
    required String? offset,
    required int? cursorNext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#mainList, [], {
              #type: type,
              #oid: oid,
              #mode: mode,
              #offset: offset,
              #cursorNext: cursorNext,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreMainListReply>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreMainListReply>>(
                    this,
                    Invocation.method(#mainList, [], {
                      #type: type,
                      #oid: oid,
                      #mode: mode,
                      #offset: offset,
                      #cursorNext: cursorNext,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreMainListReply>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreDetailListReply>> detailList({
    int? type = 1,
    required int? oid,
    required int? root,
    required int? rpid,
    required _i5.CoreMode? mode,
    required String? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#detailList, [], {
              #type: type,
              #oid: oid,
              #root: root,
              #rpid: rpid,
              #mode: mode,
              #offset: offset,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreDetailListReply>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreDetailListReply>>(
                    this,
                    Invocation.method(#detailList, [], {
                      #type: type,
                      #oid: oid,
                      #root: root,
                      #rpid: rpid,
                      #mode: mode,
                      #offset: offset,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreDetailListReply>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreDialogListReply>> dialogList({
    int? type = 1,
    required int? oid,
    required int? root,
    required int? dialog,
    required String? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#dialogList, [], {
              #type: type,
              #oid: oid,
              #root: root,
              #dialog: dialog,
              #offset: offset,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreDialogListReply>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreDialogListReply>>(
                    this,
                    Invocation.method(#dialogList, [], {
                      #type: type,
                      #oid: oid,
                      #root: root,
                      #dialog: dialog,
                      #offset: offset,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreDialogListReply>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreSearchItemReply>> searchItem({
    required int? page,
    required _i5.CoreSearchItemType? itemType,
    required int? oid,
    int? type = 1,
    String? keyword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchItem, [], {
              #page: page,
              #itemType: itemType,
              #oid: oid,
              #type: type,
              #keyword: keyword,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreSearchItemReply>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreSearchItemReply>>(
                    this,
                    Invocation.method(#searchItem, [], {
                      #page: page,
                      #itemType: itemType,
                      #oid: oid,
                      #type: type,
                      #keyword: keyword,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreSearchItemReply>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreTranslateReplyResp>> translateReply({
    required int? type,
    required int? oid,
    required int? rpid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#translateReply, [], {
              #type: type,
              #oid: oid,
              #rpid: rpid,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreTranslateReplyResp>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreTranslateReplyResp>>(
                    this,
                    Invocation.method(#translateReply, [], {
                      #type: type,
                      #oid: oid,
                      #rpid: rpid,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreTranslateReplyResp>>);

  @override
  _i3.Future<_i4.LoadingState<void>> replyTop({
    required int? oid,
    required int? type,
    required Object? rpid,
    required bool? isUpTop,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#replyTop, [], {
              #oid: oid,
              #type: type,
              #rpid: rpid,
              #isUpTop: isUpTop,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#replyTop, [], {
                  #oid: oid,
                  #type: type,
                  #rpid: rpid,
                  #isUpTop: isUpTop,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> replySubjectModify({
    required int? oid,
    required int? type,
    required int? action,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#replySubjectModify, [], {
              #oid: oid,
              #type: type,
              #action: action,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#replySubjectModify, [], {
                  #oid: oid,
                  #type: type,
                  #action: action,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);
}
