// Mocks generated by Mockito 5.4.6 from annotations
// in skf/test/repository/search_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:skf/core/models/search_types.dart' as _i5;
import 'package:skf/core/repository/search_repository.dart' as _i2;
import 'package:skf/core/result/loading_state.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SearchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchRepository extends _i1.Mock implements _i2.SearchRepository {
  MockSearchRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreSearchSuggestModel>> searchSuggest({
    required String? term,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchSuggest, [], {#term: term}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreSearchSuggestModel>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreSearchSuggestModel>>(
                    this,
                    Invocation.method(#searchSuggest, [], {#term: term}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreSearchSuggestModel>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreSearchAllData>> searchAll({
    required String? keyword,
    required int? page,
    String? order,
    int? duration,
    int? tids,
    int? orderSort,
    int? userType,
    int? categoryId,
    int? pubBegin,
    int? pubEnd,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchAll, [], {
              #keyword: keyword,
              #page: page,
              #order: order,
              #duration: duration,
              #tids: tids,
              #orderSort: orderSort,
              #userType: userType,
              #categoryId: categoryId,
              #pubBegin: pubBegin,
              #pubEnd: pubEnd,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreSearchAllData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreSearchAllData>>(
                    this,
                    Invocation.method(#searchAll, [], {
                      #keyword: keyword,
                      #page: page,
                      #order: order,
                      #duration: duration,
                      #tids: tids,
                      #orderSort: orderSort,
                      #userType: userType,
                      #categoryId: categoryId,
                      #pubBegin: pubBegin,
                      #pubEnd: pubEnd,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreSearchAllData>>);

  @override
  _i3.Future<int?> ab2c({int? aid, String? bvid, int? part}) =>
      (super.noSuchMethod(
            Invocation.method(#ab2c, [], {#aid: aid, #bvid: bvid, #part: part}),
            returnValue: _i3.Future<int?>.value(),
          )
          as _i3.Future<int?>);

  @override
  _i3.Future<({int? cid, _i5.CoreDimension? dimension})?> ab2cWithDimension({
    int? aid,
    String? bvid,
    int? part,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#ab2cWithDimension, [], {
              #aid: aid,
              #bvid: bvid,
              #part: part,
            }),
            returnValue:
                _i3.Future<({int? cid, _i5.CoreDimension? dimension})?>.value(),
          )
          as _i3.Future<({int? cid, _i5.CoreDimension? dimension})?>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CorePgcInfoModel>> pgcInfo({
    Object? seasonId,
    Object? epId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pgcInfo, [], {#seasonId: seasonId, #epId: epId}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CorePgcInfoModel>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CorePgcInfoModel>>(
                    this,
                    Invocation.method(#pgcInfo, [], {
                      #seasonId: seasonId,
                      #epId: epId,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CorePgcInfoModel>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CorePgcInfoModel>> pugvInfo({
    Object? seasonId,
    Object? epId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pugvInfo, [], {
              #seasonId: seasonId,
              #epId: epId,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CorePgcInfoModel>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CorePgcInfoModel>>(
                    this,
                    Invocation.method(#pugvInfo, [], {
                      #seasonId: seasonId,
                      #epId: epId,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CorePgcInfoModel>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreSearchTrendingData>> searchTrending({
    int? limit = 30,
    bool? needsTop = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchTrending, [], {
              #limit: limit,
              #needsTop: needsTop,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreSearchTrendingData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreSearchTrendingData>>(
                    this,
                    Invocation.method(#searchTrending, [], {
                      #limit: limit,
                      #needsTop: needsTop,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreSearchTrendingData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreSearchRcmdData>> searchRecommend() =>
      (super.noSuchMethod(
            Invocation.method(#searchRecommend, []),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreSearchRcmdData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreSearchRcmdData>>(
                    this,
                    Invocation.method(#searchRecommend, []),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreSearchRcmdData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreTopicPubSearchData>> topicPubSearch({
    required String? keywords,
    String? content = '',
    required int? pageNum,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#topicPubSearch, [], {
              #keywords: keywords,
              #content: content,
              #pageNum: pageNum,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreTopicPubSearchData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreTopicPubSearchData>>(
                    this,
                    Invocation.method(#topicPubSearch, [], {
                      #keywords: keywords,
                      #content: content,
                      #pageNum: pageNum,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreTopicPubSearchData>>);
}
