// Mocks generated by Mockito 5.4.6 from annotations
// in skf/test/repository/sponsor_block_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:skf/core/models/sponsor_block_types.dart' as _i5;
import 'package:skf/core/repository/sponsor_block_repository.dart' as _i2;
import 'package:skf/core/result/loading_state.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SponsorBlockRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSponsorBlockRepository extends _i1.Mock
    implements _i2.SponsorBlockRepository {
  MockSponsorBlockRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.LoadingState<List<_i5.CoreSegmentItemModel>>> getSkipSegments({
    required String? bvid,
    required int? cid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSkipSegments, [], {#bvid: bvid, #cid: cid}),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<List<_i5.CoreSegmentItemModel>>
                >.value(
                  _i6.dummyValue<
                    _i4.LoadingState<List<_i5.CoreSegmentItemModel>>
                  >(
                    this,
                    Invocation.method(#getSkipSegments, [], {
                      #bvid: bvid,
                      #cid: cid,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i5.CoreSegmentItemModel>>>);

  @override
  _i3.Future<_i4.LoadingState<void>> voteOnSponsorTime({
    required String? uuid,
    int? type,
    _i5.CoreSegmentType? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#voteOnSponsorTime, [], {
              #uuid: uuid,
              #type: type,
              #category: category,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#voteOnSponsorTime, [], {
                  #uuid: uuid,
                  #type: type,
                  #category: category,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> viewedVideoSponsorTime(String? uuid) =>
      (super.noSuchMethod(
            Invocation.method(#viewedVideoSponsorTime, [uuid]),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#viewedVideoSponsorTime, [uuid]),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> uptimeStatus() =>
      (super.noSuchMethod(
            Invocation.method(#uptimeStatus, []),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#uptimeStatus, []),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreUserInfo>> userInfo(
    List<String>? query, {
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#userInfo, [query], {#userId: userId}),
            returnValue: _i3.Future<_i4.LoadingState<_i5.CoreUserInfo>>.value(
              _i6.dummyValue<_i4.LoadingState<_i5.CoreUserInfo>>(
                this,
                Invocation.method(#userInfo, [query], {#userId: userId}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreUserInfo>>);

  @override
  _i3.Future<_i4.LoadingState<List<_i5.CoreSegmentItemModel>>>
  postSkipSegments({
    required String? bvid,
    required int? cid,
    required double? videoDuration,
    required List<_i5.CorePostSegmentModel>? segments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#postSkipSegments, [], {
              #bvid: bvid,
              #cid: cid,
              #videoDuration: videoDuration,
              #segments: segments,
            }),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<List<_i5.CoreSegmentItemModel>>
                >.value(
                  _i6.dummyValue<
                    _i4.LoadingState<List<_i5.CoreSegmentItemModel>>
                  >(
                    this,
                    Invocation.method(#postSkipSegments, [], {
                      #bvid: bvid,
                      #cid: cid,
                      #videoDuration: videoDuration,
                      #segments: segments,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i5.CoreSegmentItemModel>>>);

  @override
  _i3.Future<_i4.LoadingState<String>> getPortVideo({
    required String? bvid,
    required int? cid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPortVideo, [], {#bvid: bvid, #cid: cid}),
            returnValue: _i3.Future<_i4.LoadingState<String>>.value(
              _i6.dummyValue<_i4.LoadingState<String>>(
                this,
                Invocation.method(#getPortVideo, [], {#bvid: bvid, #cid: cid}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<String>>);

  @override
  _i3.Future<_i4.LoadingState<String>> postPortVideo({
    required String? bvid,
    required int? cid,
    required String? ytbId,
    required int? videoDuration,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#postPortVideo, [], {
              #bvid: bvid,
              #cid: cid,
              #ytbId: ytbId,
              #videoDuration: videoDuration,
            }),
            returnValue: _i3.Future<_i4.LoadingState<String>>.value(
              _i6.dummyValue<_i4.LoadingState<String>>(
                this,
                Invocation.method(#postPortVideo, [], {
                  #bvid: bvid,
                  #cid: cid,
                  #ytbId: ytbId,
                  #videoDuration: videoDuration,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<String>>);
}
