// Mocks generated by Mockito 5.4.6 from annotations
// in skf/test/repository/user_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:skf/core/models/follow_data.dart' as _i7;
import 'package:skf/core/models/user_types.dart' as _i5;
import 'package:skf/core/repository/user_repository.dart' as _i2;
import 'package:skf/core/result/loading_state.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i2.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreUserInfoData>> userInfo() =>
      (super.noSuchMethod(
            Invocation.method(#userInfo, []),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreUserInfoData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreUserInfoData>>(
                    this,
                    Invocation.method(#userInfo, []),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreUserInfoData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreUserStat>> userStatOwner() =>
      (super.noSuchMethod(
            Invocation.method(#userStatOwner, []),
            returnValue: _i3.Future<_i4.LoadingState<_i5.CoreUserStat>>.value(
              _i6.dummyValue<_i4.LoadingState<_i5.CoreUserStat>>(
                this,
                Invocation.method(#userStatOwner, []),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreUserStat>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreLaterData>> seeYouLater({
    required int? page,
    int? viewed = 0,
    String? keyword = '',
    bool? asc = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#seeYouLater, [], {
              #page: page,
              #viewed: viewed,
              #keyword: keyword,
              #asc: asc,
            }),
            returnValue: _i3.Future<_i4.LoadingState<_i5.CoreLaterData>>.value(
              _i6.dummyValue<_i4.LoadingState<_i5.CoreLaterData>>(
                this,
                Invocation.method(#seeYouLater, [], {
                  #page: page,
                  #viewed: viewed,
                  #keyword: keyword,
                  #asc: asc,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreLaterData>>);

  @override
  _i3.Future<_i4.LoadingState<void>> toViewLater({String? bvid, Object? aid}) =>
      (super.noSuchMethod(
            Invocation.method(#toViewLater, [], {#bvid: bvid, #aid: aid}),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#toViewLater, [], {#bvid: bvid, #aid: aid}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> toViewDel({required String? aids}) =>
      (super.noSuchMethod(
            Invocation.method(#toViewDel, [], {#aids: aids}),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#toViewDel, [], {#aids: aids}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> toViewClear([int? cleanType]) =>
      (super.noSuchMethod(
            Invocation.method(#toViewClear, [cleanType]),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#toViewClear, [cleanType]),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreHistoryData>> historyList({
    required String? type,
    int? max,
    int? viewAt,
    Object? account,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#historyList, [], {
              #type: type,
              #max: max,
              #viewAt: viewAt,
              #account: account,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreHistoryData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreHistoryData>>(
                    this,
                    Invocation.method(#historyList, [], {
                      #type: type,
                      #max: max,
                      #viewAt: viewAt,
                      #account: account,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreHistoryData>>);

  @override
  _i3.Future<_i4.LoadingState<void>> pauseHistory(
    bool? switchStatus, {
    Object? account,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pauseHistory,
              [switchStatus],
              {#account: account},
            ),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(
                  #pauseHistory,
                  [switchStatus],
                  {#account: account},
                ),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<bool>> historyStatus({Object? account}) =>
      (super.noSuchMethod(
            Invocation.method(#historyStatus, [], {#account: account}),
            returnValue: _i3.Future<_i4.LoadingState<bool>>.value(
              _i6.dummyValue<_i4.LoadingState<bool>>(
                this,
                Invocation.method(#historyStatus, [], {#account: account}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<bool>>);

  @override
  _i3.Future<_i4.LoadingState<void>> clearHistory({Object? account}) =>
      (super.noSuchMethod(
            Invocation.method(#clearHistory, [], {#account: account}),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#clearHistory, [], {#account: account}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> delHistory(
    String? kid, {
    Object? account,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delHistory, [kid], {#account: account}),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#delHistory, [kid], {#account: account}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreHistoryData>> searchHistory({
    required int? pn,
    required String? keyword,
    Object? account,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchHistory, [], {
              #pn: pn,
              #keyword: keyword,
              #account: account,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreHistoryData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreHistoryData>>(
                    this,
                    Invocation.method(#searchHistory, [], {
                      #pn: pn,
                      #keyword: keyword,
                      #account: account,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreHistoryData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreRelationData>> userRelation(int? mid) =>
      (super.noSuchMethod(
            Invocation.method(#userRelation, [mid]),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreRelationData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreRelationData>>(
                    this,
                    Invocation.method(#userRelation, [mid]),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreRelationData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreSubData>> userSubFolder({
    required int? mid,
    required int? pn,
    required int? ps,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#userSubFolder, [], {
              #mid: mid,
              #pn: pn,
              #ps: ps,
            }),
            returnValue: _i3.Future<_i4.LoadingState<_i5.CoreSubData>>.value(
              _i6.dummyValue<_i4.LoadingState<_i5.CoreSubData>>(
                this,
                Invocation.method(#userSubFolder, [], {
                  #mid: mid,
                  #pn: pn,
                  #ps: ps,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreSubData>>);

  @override
  _i3.Future<_i4.LoadingState<List<_i5.CoreVideoTagItem>?>> videoTags({
    required String? bvid,
    Object? cid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#videoTags, [], {#bvid: bvid, #cid: cid}),
            returnValue:
                _i3.Future<_i4.LoadingState<List<_i5.CoreVideoTagItem>?>>.value(
                  _i6.dummyValue<_i4.LoadingState<List<_i5.CoreVideoTagItem>?>>(
                    this,
                    Invocation.method(#videoTags, [], {#bvid: bvid, #cid: cid}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i5.CoreVideoTagItem>?>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreMediaListData>> getMediaList({
    required Object? type,
    required Object? bizId,
    required int? ps,
    Object? oid,
    int? otype,
    bool? withCurrent = false,
    bool? desc = true,
    dynamic sortField = 1,
    bool? direction = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMediaList, [], {
              #type: type,
              #bizId: bizId,
              #ps: ps,
              #oid: oid,
              #otype: otype,
              #withCurrent: withCurrent,
              #desc: desc,
              #sortField: sortField,
              #direction: direction,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreMediaListData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreMediaListData>>(
                    this,
                    Invocation.method(#getMediaList, [], {
                      #type: type,
                      #bizId: bizId,
                      #ps: ps,
                      #oid: oid,
                      #otype: otype,
                      #withCurrent: withCurrent,
                      #desc: desc,
                      #sortField: sortField,
                      #direction: direction,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreMediaListData>>);

  @override
  _i3.Future<_i4.LoadingState<num?>> getCoin() =>
      (super.noSuchMethod(
            Invocation.method(#getCoin, []),
            returnValue: _i3.Future<_i4.LoadingState<num?>>.value(
              _i6.dummyValue<_i4.LoadingState<num?>>(
                this,
                Invocation.method(#getCoin, []),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<num?>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreCoinLogData>> coinLog() =>
      (super.noSuchMethod(
            Invocation.method(#coinLog, []),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreCoinLogData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreCoinLogData>>(
                    this,
                    Invocation.method(#coinLog, []),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreCoinLogData>>);

  @override
  _i3.Future<_i4.LoadingState<void>> dynamicReport({
    required Object? mid,
    required Object? dynId,
    required int? reasonType,
    String? reasonDesc,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#dynamicReport, [], {
              #mid: mid,
              #dynId: dynId,
              #reasonType: reasonType,
              #reasonDesc: reasonDesc,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#dynamicReport, [], {
                  #mid: mid,
                  #dynId: dynId,
                  #reasonType: reasonType,
                  #reasonDesc: reasonDesc,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreSpaceSettingData>> spaceSetting() =>
      (super.noSuchMethod(
            Invocation.method(#spaceSetting, []),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreSpaceSettingData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreSpaceSettingData>>(
                    this,
                    Invocation.method(#spaceSetting, []),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreSpaceSettingData>>);

  @override
  _i3.Future<_i4.LoadingState<void>> spaceSettingMod(
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#spaceSettingMod, [data]),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#spaceSettingMod, [data]),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> spaceReserve({
    required Object? sid,
    required bool? isFollow,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#spaceReserve, [], {
              #sid: sid,
              #isFollow: isFollow,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#spaceReserve, [], {
                  #sid: sid,
                  #isFollow: isFollow,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> vipExpAdd() =>
      (super.noSuchMethod(
            Invocation.method(#vipExpAdd, []),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#vipExpAdd, []),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreLoginLogData>> loginLog() =>
      (super.noSuchMethod(
            Invocation.method(#loginLog, []),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreLoginLogData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreLoginLogData>>(
                    this,
                    Invocation.method(#loginLog, []),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreLoginLogData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreCoinLogData>> expLog() =>
      (super.noSuchMethod(
            Invocation.method(#expLog, []),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreCoinLogData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreCoinLogData>>(
                    this,
                    Invocation.method(#expLog, []),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreCoinLogData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreUserRealNameData>> getUserRealName(
    Object? mid,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserRealName, [mid]),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreUserRealNameData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreUserRealNameData>>(
                    this,
                    Invocation.method(#getUserRealName, [mid]),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreUserRealNameData>>);

  @override
  _i3.Future<_i4.LoadingState<_i7.CoreFollowData>> followedUp({
    required Object? mid,
    required int? pn,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#followedUp, [], {#mid: mid, #pn: pn}),
            returnValue: _i3.Future<_i4.LoadingState<_i7.CoreFollowData>>.value(
              _i6.dummyValue<_i4.LoadingState<_i7.CoreFollowData>>(
                this,
                Invocation.method(#followedUp, [], {#mid: mid, #pn: pn}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<_i7.CoreFollowData>>);

  @override
  _i3.Future<_i4.LoadingState<_i7.CoreFollowData>> sameFollowing({
    required Object? mid,
    int? pn,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sameFollowing, [], {#mid: mid, #pn: pn}),
            returnValue: _i3.Future<_i4.LoadingState<_i7.CoreFollowData>>.value(
              _i6.dummyValue<_i4.LoadingState<_i7.CoreFollowData>>(
                this,
                Invocation.method(#sameFollowing, [], {#mid: mid, #pn: pn}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<_i7.CoreFollowData>>);
}
