// Mocks generated by Mockito 5.4.6 from annotations
// in skf/test/repository/video_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:skf/core/models/video_types.dart' as _i5;
import 'package:skf/core/repository/video_repository.dart' as _i2;
import 'package:skf/core/result/loading_state.dart' as _i4;
import 'package:skf/core/utils/subtitle_utils.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [VideoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoRepository extends _i1.Mock implements _i2.VideoRepository {
  MockVideoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.LoadingState<List<_i5.CoreRcmdVideoItemModel>>> rcmdVideoList({
    required int? ps,
    required int? freshIdx,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rcmdVideoList, [], {
              #ps: ps,
              #freshIdx: freshIdx,
            }),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<List<_i5.CoreRcmdVideoItemModel>>
                >.value(
                  _i6.dummyValue<
                    _i4.LoadingState<List<_i5.CoreRcmdVideoItemModel>>
                  >(
                    this,
                    Invocation.method(#rcmdVideoList, [], {
                      #ps: ps,
                      #freshIdx: freshIdx,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i5.CoreRcmdVideoItemModel>>>);

  @override
  _i3.Future<_i4.LoadingState<List<_i5.CoreRcmdVideoItemAppModel>>>
  rcmdVideoListApp({required int? freshIdx}) =>
      (super.noSuchMethod(
            Invocation.method(#rcmdVideoListApp, [], {#freshIdx: freshIdx}),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<List<_i5.CoreRcmdVideoItemAppModel>>
                >.value(
                  _i6.dummyValue<
                    _i4.LoadingState<List<_i5.CoreRcmdVideoItemAppModel>>
                  >(
                    this,
                    Invocation.method(#rcmdVideoListApp, [], {
                      #freshIdx: freshIdx,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i5.CoreRcmdVideoItemAppModel>>>);

  @override
  _i3.Future<_i4.LoadingState<List<_i5.CoreHotVideoItemModel>>> hotVideoList({
    required int? pn,
    required int? ps,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#hotVideoList, [], {#pn: pn, #ps: ps}),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<List<_i5.CoreHotVideoItemModel>>
                >.value(
                  _i6.dummyValue<
                    _i4.LoadingState<List<_i5.CoreHotVideoItemModel>>
                  >(
                    this,
                    Invocation.method(#hotVideoList, [], {#pn: pn, #ps: ps}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i5.CoreHotVideoItemModel>>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CorePlayUrlModel>> videoUrl({
    int? avid,
    String? bvid,
    required int? cid,
    int? qn,
    dynamic epid,
    dynamic seasonId,
    required bool? tryLook,
    required _i5.CoreVideoType? videoType,
    String? language,
    bool? voiceBalance = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#videoUrl, [], {
              #avid: avid,
              #bvid: bvid,
              #cid: cid,
              #qn: qn,
              #epid: epid,
              #seasonId: seasonId,
              #tryLook: tryLook,
              #videoType: videoType,
              #language: language,
              #voiceBalance: voiceBalance,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CorePlayUrlModel>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CorePlayUrlModel>>(
                    this,
                    Invocation.method(#videoUrl, [], {
                      #avid: avid,
                      #bvid: bvid,
                      #cid: cid,
                      #qn: qn,
                      #epid: epid,
                      #seasonId: seasonId,
                      #tryLook: tryLook,
                      #videoType: videoType,
                      #language: language,
                      #voiceBalance: voiceBalance,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CorePlayUrlModel>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreVideoDetailData>> videoIntro({
    required String? bvid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#videoIntro, [], {#bvid: bvid}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreVideoDetailData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreVideoDetailData>>(
                    this,
                    Invocation.method(#videoIntro, [], {#bvid: bvid}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreVideoDetailData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreVideoRelation>> videoRelation({
    required String? bvid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#videoRelation, [], {#bvid: bvid}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreVideoRelation>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreVideoRelation>>(
                    this,
                    Invocation.method(#videoRelation, [], {#bvid: bvid}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreVideoRelation>>);

  @override
  _i3.Future<_i4.LoadingState<List<_i5.CoreHotVideoItemModel>?>>
  relatedVideoList({required String? bvid}) =>
      (super.noSuchMethod(
            Invocation.method(#relatedVideoList, [], {#bvid: bvid}),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<List<_i5.CoreHotVideoItemModel>?>
                >.value(
                  _i6.dummyValue<
                    _i4.LoadingState<List<_i5.CoreHotVideoItemModel>?>
                  >(
                    this,
                    Invocation.method(#relatedVideoList, [], {#bvid: bvid}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i5.CoreHotVideoItemModel>?>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CorePgcLCF>> pgcLikeCoinFav({
    required Object? epId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pgcLikeCoinFav, [], {#epId: epId}),
            returnValue: _i3.Future<_i4.LoadingState<_i5.CorePgcLCF>>.value(
              _i6.dummyValue<_i4.LoadingState<_i5.CorePgcLCF>>(
                this,
                Invocation.method(#pgcLikeCoinFav, [], {#epId: epId}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CorePgcLCF>>);

  @override
  _i3.Future<_i4.LoadingState<void>> coinVideo({
    required String? bvid,
    required int? multiply,
    int? selectLike = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#coinVideo, [], {
              #bvid: bvid,
              #multiply: multiply,
              #selectLike: selectLike,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#coinVideo, [], {
                  #bvid: bvid,
                  #multiply: multiply,
                  #selectLike: selectLike,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CorePgcTriple>> pgcTriple({
    required Object? epId,
    Object? seasonId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pgcTriple, [], {
              #epId: epId,
              #seasonId: seasonId,
            }),
            returnValue: _i3.Future<_i4.LoadingState<_i5.CorePgcTriple>>.value(
              _i6.dummyValue<_i4.LoadingState<_i5.CorePgcTriple>>(
                this,
                Invocation.method(#pgcTriple, [], {
                  #epId: epId,
                  #seasonId: seasonId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CorePgcTriple>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreUgcTriple>> ugcTriple({
    required String? bvid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#ugcTriple, [], {#bvid: bvid}),
            returnValue: _i3.Future<_i4.LoadingState<_i5.CoreUgcTriple>>.value(
              _i6.dummyValue<_i4.LoadingState<_i5.CoreUgcTriple>>(
                this,
                Invocation.method(#ugcTriple, [], {#bvid: bvid}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreUgcTriple>>);

  @override
  _i3.Future<_i4.LoadingState<String>> likeVideo({
    required String? bvid,
    required bool? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#likeVideo, [], {#bvid: bvid, #type: type}),
            returnValue: _i3.Future<_i4.LoadingState<String>>.value(
              _i6.dummyValue<_i4.LoadingState<String>>(
                this,
                Invocation.method(#likeVideo, [], {#bvid: bvid, #type: type}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<String>>);

  @override
  _i3.Future<_i4.LoadingState<void>> dislikeVideo({
    required String? bvid,
    required bool? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#dislikeVideo, [], {#bvid: bvid, #type: type}),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#dislikeVideo, [], {
                  #bvid: bvid,
                  #type: type,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> relationMod({
    required int? mid,
    required int? act,
    required int? reSrc,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#relationMod, [], {
              #mid: mid,
              #act: act,
              #reSrc: reSrc,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#relationMod, [], {
                  #mid: mid,
                  #act: act,
                  #reSrc: reSrc,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> feedDislike({
    required String? goto,
    required int? id,
    int? reasonId,
    int? feedbackId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#feedDislike, [], {
              #goto: goto,
              #id: id,
              #reasonId: reasonId,
              #feedbackId: feedbackId,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#feedDislike, [], {
                  #goto: goto,
                  #id: id,
                  #reasonId: reasonId,
                  #feedbackId: feedbackId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<void>> feedDislikeCancel({
    required String? goto,
    required int? id,
    int? reasonId,
    int? feedbackId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#feedDislikeCancel, [], {
              #goto: goto,
              #id: id,
              #reasonId: reasonId,
              #feedbackId: feedbackId,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#feedDislikeCancel, [], {
                  #goto: goto,
                  #id: id,
                  #reasonId: reasonId,
                  #feedbackId: feedbackId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreReplyInfo?>> replyAdd({
    required int? type,
    required int? oid,
    required String? message,
    int? root,
    int? parent,
    List<dynamic>? pictures,
    bool? syncToDynamic = false,
    Map<String, int>? atNameToMid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#replyAdd, [], {
              #type: type,
              #oid: oid,
              #message: message,
              #root: root,
              #parent: parent,
              #pictures: pictures,
              #syncToDynamic: syncToDynamic,
              #atNameToMid: atNameToMid,
            }),
            returnValue: _i3.Future<_i4.LoadingState<_i5.CoreReplyInfo?>>.value(
              _i6.dummyValue<_i4.LoadingState<_i5.CoreReplyInfo?>>(
                this,
                Invocation.method(#replyAdd, [], {
                  #type: type,
                  #oid: oid,
                  #message: message,
                  #root: root,
                  #parent: parent,
                  #pictures: pictures,
                  #syncToDynamic: syncToDynamic,
                  #atNameToMid: atNameToMid,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreReplyInfo?>>);

  @override
  _i3.Future<_i4.LoadingState<void>> replyDel({
    required int? type,
    required int? oid,
    required int? rpid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#replyDel, [], {
              #type: type,
              #oid: oid,
              #rpid: rpid,
            }),
            returnValue: _i3.Future<_i4.LoadingState<void>>.value(
              _i6.dummyValue<_i4.LoadingState<void>>(
                this,
                Invocation.method(#replyDel, [], {
                  #type: type,
                  #oid: oid,
                  #rpid: rpid,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<void>>);

  @override
  _i3.Future<_i4.LoadingState<String>> pgcAdd({int? seasonId}) =>
      (super.noSuchMethod(
            Invocation.method(#pgcAdd, [], {#seasonId: seasonId}),
            returnValue: _i3.Future<_i4.LoadingState<String>>.value(
              _i6.dummyValue<_i4.LoadingState<String>>(
                this,
                Invocation.method(#pgcAdd, [], {#seasonId: seasonId}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<String>>);

  @override
  _i3.Future<_i4.LoadingState<String>> pgcDel({int? seasonId}) =>
      (super.noSuchMethod(
            Invocation.method(#pgcDel, [], {#seasonId: seasonId}),
            returnValue: _i3.Future<_i4.LoadingState<String>>.value(
              _i6.dummyValue<_i4.LoadingState<String>>(
                this,
                Invocation.method(#pgcDel, [], {#seasonId: seasonId}),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<String>>);

  @override
  _i3.Future<_i4.LoadingState<String>> pgcUpdate({
    required String? seasonId,
    required int? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pgcUpdate, [], {
              #seasonId: seasonId,
              #status: status,
            }),
            returnValue: _i3.Future<_i4.LoadingState<String>>.value(
              _i6.dummyValue<_i4.LoadingState<String>>(
                this,
                Invocation.method(#pgcUpdate, [], {
                  #seasonId: seasonId,
                  #status: status,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<String>>);

  @override
  _i3.Future<_i4.LoadingState<String>> onlineTotal({
    int? aid,
    String? bvid,
    required int? cid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#onlineTotal, [], {
              #aid: aid,
              #bvid: bvid,
              #cid: cid,
            }),
            returnValue: _i3.Future<_i4.LoadingState<String>>.value(
              _i6.dummyValue<_i4.LoadingState<String>>(
                this,
                Invocation.method(#onlineTotal, [], {
                  #aid: aid,
                  #bvid: bvid,
                  #cid: cid,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.LoadingState<String>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreAiConclusionData>> aiConclusion({
    required String? bvid,
    required int? cid,
    int? upMid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#aiConclusion, [], {
              #bvid: bvid,
              #cid: cid,
              #upMid: upMid,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreAiConclusionData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreAiConclusionData>>(
                    this,
                    Invocation.method(#aiConclusion, [], {
                      #bvid: bvid,
                      #cid: cid,
                      #upMid: upMid,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreAiConclusionData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CorePlayInfoData>> playInfo({
    String? aid,
    String? bvid,
    required int? cid,
    dynamic seasonId,
    dynamic epId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#playInfo, [], {
              #aid: aid,
              #bvid: bvid,
              #cid: cid,
              #seasonId: seasonId,
              #epId: epId,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CorePlayInfoData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CorePlayInfoData>>(
                    this,
                    Invocation.method(#playInfo, [], {
                      #aid: aid,
                      #bvid: bvid,
                      #cid: cid,
                      #seasonId: seasonId,
                      #epId: epId,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CorePlayInfoData>>);

  @override
  _i3.Future<String?> vttSubtitles(
    String? subtitleUrl, {
    _i7.SubtitleFormat? format = _i7.SubtitleFormat.vtt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#vttSubtitles, [subtitleUrl], {#format: format}),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<_i4.LoadingState<List<_i5.CoreHotVideoItemModel>>>
  getRankVideoList(int? rid) =>
      (super.noSuchMethod(
            Invocation.method(#getRankVideoList, [rid]),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<List<_i5.CoreHotVideoItemModel>>
                >.value(
                  _i6.dummyValue<
                    _i4.LoadingState<List<_i5.CoreHotVideoItemModel>>
                  >(this, Invocation.method(#getRankVideoList, [rid])),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i5.CoreHotVideoItemModel>>>);

  @override
  _i3.Future<_i4.LoadingState<List<_i5.CorePgcRankItemModel>?>> pgcRankList({
    int? day = 3,
    required int? seasonType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pgcRankList, [], {
              #day: day,
              #seasonType: seasonType,
            }),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<List<_i5.CorePgcRankItemModel>?>
                >.value(
                  _i6.dummyValue<
                    _i4.LoadingState<List<_i5.CorePgcRankItemModel>?>
                  >(
                    this,
                    Invocation.method(#pgcRankList, [], {
                      #day: day,
                      #seasonType: seasonType,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i5.CorePgcRankItemModel>?>>);

  @override
  _i3.Future<_i4.LoadingState<List<_i5.CorePgcRankItemModel>?>>
  pgcSeasonRankList({int? day = 3, required int? seasonType}) =>
      (super.noSuchMethod(
            Invocation.method(#pgcSeasonRankList, [], {
              #day: day,
              #seasonType: seasonType,
            }),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<List<_i5.CorePgcRankItemModel>?>
                >.value(
                  _i6.dummyValue<
                    _i4.LoadingState<List<_i5.CorePgcRankItemModel>?>
                  >(
                    this,
                    Invocation.method(#pgcSeasonRankList, [], {
                      #day: day,
                      #seasonType: seasonType,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<List<_i5.CorePgcRankItemModel>?>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreVideoShotData>> videoshot({
    required String? bvid,
    required int? cid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#videoshot, [], {#bvid: bvid, #cid: cid}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreVideoShotData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreVideoShotData>>(
                    this,
                    Invocation.method(#videoshot, [], {#bvid: bvid, #cid: cid}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreVideoShotData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CoreVideoNoteData>> getVideoNoteList({
    dynamic oid,
    dynamic uperMid,
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getVideoNoteList, [], {
              #oid: oid,
              #uperMid: uperMid,
              #page: page,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CoreVideoNoteData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CoreVideoNoteData>>(
                    this,
                    Invocation.method(#getVideoNoteList, [], {
                      #oid: oid,
                      #uperMid: uperMid,
                      #page: page,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CoreVideoNoteData>>);

  @override
  _i3.Future<_i4.LoadingState<List<_i5.CorePopularSeriesListItem>?>>
  popularSeriesList() =>
      (super.noSuchMethod(
            Invocation.method(#popularSeriesList, []),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<List<_i5.CorePopularSeriesListItem>?>
                >.value(
                  _i6.dummyValue<
                    _i4.LoadingState<List<_i5.CorePopularSeriesListItem>?>
                  >(this, Invocation.method(#popularSeriesList, [])),
                ),
          )
          as _i3.Future<
            _i4.LoadingState<List<_i5.CorePopularSeriesListItem>?>
          >);

  @override
  _i3.Future<_i4.LoadingState<_i5.CorePopularSeriesOneData>> popularSeriesOne({
    required int? number,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#popularSeriesOne, [], {#number: number}),
            returnValue:
                _i3.Future<
                  _i4.LoadingState<_i5.CorePopularSeriesOneData>
                >.value(
                  _i6.dummyValue<
                    _i4.LoadingState<_i5.CorePopularSeriesOneData>
                  >(
                    this,
                    Invocation.method(#popularSeriesOne, [], {#number: number}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CorePopularSeriesOneData>>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CorePopularPreciousData>> popularPrecious({
    required int? page,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#popularPrecious, [], {#page: page}),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CorePopularPreciousData>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CorePopularPreciousData>>(
                    this,
                    Invocation.method(#popularPrecious, [], {#page: page}),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CorePopularPreciousData>>);

  @override
  _i3.Future<void> historyReport({
    required Object? aid,
    required Object? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#historyReport, [], {#aid: aid, #type: type}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> heartBeat({
    Object? aid,
    Object? bvid,
    required Object? cid,
    required Object? progress,
    Object? epid,
    Object? seasonId,
    Object? subType,
    required _i5.CoreVideoType? videoType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#heartBeat, [], {
              #aid: aid,
              #bvid: bvid,
              #cid: cid,
              #progress: progress,
              #epid: epid,
              #seasonId: seasonId,
              #subType: subType,
              #videoType: videoType,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> roomEntryAction({required Object? roomId}) =>
      (super.noSuchMethod(
            Invocation.method(#roomEntryAction, [], {#roomId: roomId}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> medialistHistory({
    required int? desc,
    required Object? oid,
    required Object? upperMid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#medialistHistory, [], {
              #desc: desc,
              #oid: oid,
              #upperMid: upperMid,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.LoadingState<_i5.CorePlayUrlModel>> tvPlayUrl({
    required int? cid,
    required int? objectId,
    required int? playurlType,
    int? qn,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#tvPlayUrl, [], {
              #cid: cid,
              #objectId: objectId,
              #playurlType: playurlType,
              #qn: qn,
            }),
            returnValue:
                _i3.Future<_i4.LoadingState<_i5.CorePlayUrlModel>>.value(
                  _i6.dummyValue<_i4.LoadingState<_i5.CorePlayUrlModel>>(
                    this,
                    Invocation.method(#tvPlayUrl, [], {
                      #cid: cid,
                      #objectId: objectId,
                      #playurlType: playurlType,
                      #qn: qn,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.LoadingState<_i5.CorePlayUrlModel>>);
}
